### ISSUE TITLE
Issue with stroke for "tension"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#100]
In the current `dict.json` file, there are the following strokes for the word "tension", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"TEPBGS": "tension",
"TEPBLGS": "tension",
"TEPGS": "tension",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "tension" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L8253

Although Plover says it's a valid stroke, I am wondering whether perhaps `TEPGS` is a mis-stroke due to it not having the full `PB` stroke for "n" included in its stroke, which is what I would have expected for the word "tension". Therefore, I would propose:

- Removing `"TEPGS": "tension",` from `dict.json`
- Adding `"TEPGS": "tension",` to `bad-habits.json`
- Changing the stroke for "tension" in `top-10000-project-gutenberg-words.json` from `TEPGS` to `TEPBGS`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti, those changes look good to me.
