### ISSUE TITLE
Issue with stroke for "concentration"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#101]
In the current `dict.json` file, there are the following single-stroke entries for the word "concentration", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"SKRA*EUGS": "concentration",
"SKRAEUGS": "concentration",
"SKRAUGS": "concentration",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "concentration" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L8682

Although Plover says it's a valid stroke, I am wondering whether perhaps `SKRAUGS` is a mis-stroke due to it not having an elongated "ā" sound (`AEU`) included in its stroke, which is what I would have expected for the word "concentration". So, I would propose:

- Removing `"SKRAUGS": "concentration",` from `dict.json`
- Adding `"SKRAUGS": "concentration",` to `bad-habits.json`
- Changing the stroke for "concentration" in `top-10000-project-gutenberg-words.json` from `SKRAUGS` to `SKRAEUGS`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti, those changes look good to me.
