### ISSUE TITLE
Issue with strokes for "find*"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#103]
In the current `dict.json` file, there are the following strokes entries for words starting with "find", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"TPAOEUPBD": "find",
"TPEUPBD": "find",
"TPAOEUPB/TKER": "finder",
"TPAOEUPBD/*ER": "finder",
"TPAOEURPBD": "finder",
"TPAOEUPBD/ERS": "finders",
"TPAOEPBGD": "finding",
"TPAOEUBD/-G": "finding",
"TPAOEUPBGD": "finding",
"TPAOEUPBD/-GS": "findings",
"TPAOEUPBGDZ": "findings",
"TPHAOEUPBD": "find it",
"TPAOEUPBDZ": "finds",
"TPHAOEUPBD/T-S": "find that it's",
```

Most of these entries use the stroke `AOEU` for the "ī" sound in "find", and this would lead  me to believe that perhaps entries that shorten that sound, like `"TPEUPBD": "find"` could be mis-strokes.

Entries that use the shortened "ī" sound (in different ways) for "find" are present in many of the entries in other dictionaries:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L201

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L1377

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-200-words-spoken-on-tv.json#L156

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-1000-words.json#L201

So, my questions are:

- Are strokes that use anything other than `AOEU` for "find*" mis-strokes, and hence should be moved to`bad-habits.json`?
- If so, should the entries in all the other dictionaries linked to above be changed to their `AOEU`-using counterparts?

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. The entries using the short "i" sound might be considered briefs as well as misstrokes. To make it predictable for beginners learning stenography, it might be worth switching them to the long "i" sound, with a note in the commit message that they can be briefs as well as misstrokes.

**Comment by paulfioravanti** [comment]
Thanks, @didoesdigital. In that case, I'll put in a PR that leaves `dict.json` alone as the short "i" sounds are not considered mis-strokes, and just change out the entries in four entries mentioned above.
