### ISSUE TITLE
Issue with stroke for "completely"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#104]
In the current `dict.json` file, there are the following strokes for the word "completely", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"KPHRAOELT": "completely",
"KPHRAOET/HREU": "completely",
"KPHRELT": "completely",
"KPWHRAOELT": "completely",
"TKPHRAOELT": "completely",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "completely" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L1587

Although Plover says it's a valid stroke, I feel that `"KPHRAOELT": "completely"` with the elongated "ē" sound (`AOE`) is a more accurate entry pronunciation-wise (and all the other entries use `AOE`), and so would like to propose:

- Removing `"KPHRELT": "completely",` from `dict.json`
- Adding `"KPHRELT": "completely",` to `bad-habits.json`
- Changing the stroke for "completely" in `top-10000-project-gutenberg-words.json` from `KPHRELT` to `KPHRAOELT`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti . That sounds good to me. The keys for the long "e" sound also matches with entries for:

```
"KPHRAOELT": "completely",
"KPHRAOELS": "completion",
"KPHRAOEGT": "completing",
"KPHRAOEGS": "completion",
"KPHRAOETS": "completes",
"KPHRAOETD": "completed",
```
