### ISSUE TITLE
Issue with stroke for "leading"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#105]
In the current `dict.json` file, there are the following strokes for the word "leading", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"HRAEGD": "leading",
"HRAOED/-G": "leading",
"HRAOEGD": "leading",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "leading" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L1345

This entry can also be found in `ux-design.json`:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/ux-design.json#L160

Although Plover says it's a valid stroke, I feel that `"HRAOEGD": "leading"` with the elongated "ē" sound (`AOE`) is a more accurate entry pronunciation-wise (and all the other entries use `AOE`), and so would like to propose:

- Changing the stroke for "leading" in `top-10000-project-gutenberg-words.json` from `HRAEGD` to `HRAOEGD`

Since `"HRAEGD": "leading"` is used in `ux-design.json`, which I'm assuming is more of a custom, opinionated dictionary, depending on how  you feel about the `"HRAEGD": "leading"` entry:

- Add `"HRAEGD": "leading"` to `bad-habits.json` (specifically marking it as a mis-stroke)
  - Hence, changing the stroke for "completely" in `ux-design.json` from `HRAEGD` to `HRAOEGD` as well
  - And removing `"HRAEGD": "leading"` from `dict.json`
- Or, doing nothing

**Comment by didoesdigital** [comment]
The `AE` vowel keys for "leading" and "lead" make sense if you ever wanted to use the [`AE` disambiguation rule](https://sites.google.com/site/ploverdoc/lesson-3-english-sounds/3A-vowels/3a-4-vowel-disambiguators) to distinguish them from "leed" or "lede".

In the context of design, ["leading" in typography may be pronounced "ledding", rhyming with "bedding"](https://en.wikipedia.org/wiki/Leading#Origins).

For these reasons, I'd prefer to leave "leading" as it is.

**Comment by paulfioravanti** [comment]
Sounds good to me. Thank you for those links!
