### ISSUE TITLE
Add stroke for "editor"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#106]
In the current `dict.json` file, there are the following strokes for the word "editor", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"ED/EUT/O*R": "editor",
"ED/TOR": "editor",
"OERTD": "editor",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "editor" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L3747

Plover would now seem to have two more entries for "editor" that are not currently in the dictionaries:

```
editor:
   ERTD
   ETD/O*R
```

I think the `ERTD` stroke should be added to the dictionaries and should be the stroke used in Typey-Type due to less mental overhead when it comes to the inversions ie I only have to think about `RT` after `D`, rather than also having to think about `O` after the word has finished (if that makes sense...).

Anyway, what I would like to propose is:

- Addition of `"ERTD": "editor"` (and `"ETD/O*R": "editor"`?) to `dict.json`
- Change "editor" stroke entry in `top-10000-project-gutenberg-words.json` from `"OERTD": "editor",` to `"ERTD": "editor"`.

**Comment by didoesdigital** [comment]
Thanks, @paulfioravanti. Both additions and update sounds good. Are there any words like editors or editorial that might need updates?

**Comment by paulfioravanti** [comment]
"editorial", "Editorial", "editorials", and "editorialize" entries in the dictionaries look good compared to Plover, but it looks like "editors" could be updated since it now has three single-stroke entries, none of which are currently in the dictionaries:

```
editors:
   ERTDZ
   ERTSD
   ERTSDZ
```

Here, I would propose:

- addition of these three entries to `dict.json`
- As for the Gutenberg entry, I don't mind the current
  https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L8829
entry, but if it should change to single stroke for some consistency with "editor", my vote would be for `ERTSDZ` since I find `TDZ` difficult to stroke with a single pinky finger without also accidentally hitting `S`, and similarly `TSD` is hard to stroke with a pinky without also accidentally hitting `Z`.

What do you think?

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti , that all sounds great to me (additions and `ERTSDZ`).
