### ISSUE TITLE
Issue with stroke for "amidst"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#107]
In the current `dict.json` file, there are the following strokes for the word "amidst", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"A/PH*EUFD": "amidst",
"A/PH*EUS": "amidst",
"A/PHEUTDZ": "amidst",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "amidst" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L3949

I know that as a general rule, Typey-Type prioritises entries without `*`, but I think this word could be marked as an exception due to the awkwardness of the `A/PHEUTDZ` stroke. Particularly, the pinky finger being technically responsible for stroking `TDZ`, which at least I've found very difficult to do without accidentally also pressing `S` (or should the thinking for this stroke be that the right ring finger should be temporarily re-assigned responsiblity for pressing `T`...?).

I would be happy to have the entry in `top-10000-project-gutenberg-words.json` be changed to either of the alternatives, but I would lean a bit more towards `A/PH*EUFD`, even though its a letter more than `A/PH*EUS` _and_ a pinky reach for the `D` key, due to it _slightly_ more conforming to my mental pronunciation of "amidst".

**Comment by didoesdigital** [comment]
Let's move ` "A/PHEUTDZ": "amidst", ` to bad habits as it looks like a "Philly shift" to me where, yes, you would move your ring finger, which is not part of Plover theory.

Either of those other entries seem fine to me.

**Comment by paulfioravanti** [comment]
TIL ["Philly Shift"](https://www.artofchording.com/layout/d-and-z.html#the-d-and-z-keys). Thanks!
