### ISSUE TITLE
No Plover entry for "tiding"/"tidings"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#108]
In the current `nouns.json` and `top-10000-project-gutenberg-words.json` file (but not `dict.json`?), there is the following stroke for the word "tidings":

```json
"TAOEUGD/-S": "tidings"
```

Unfortunately, this entry does not seem to exist in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), nor does "tiding" singular.

So, my questions are:

- Should these two entries be changed to their fingerspelling (`T*/*EU/TK*/*EU/TPH*/TKPW*/S*`)?
- Should an entry/entries for "tiding"/"tidings" be added to `dict.json`?

**Comment by didoesdigital** [comment]
Thanks for this @paulfioravanti . I'm puzzled by how `"TAOEUGD/-S": "tidings"` came to be. I could understand how `"TAOEUD/-G": "tiding"` and `"TAOEUD/-G/-S": "tidings"` might work using orthography rules and following from that you might create a brief using the [suffix folding with inversion](https://github.com/openstenoproject/plover/wiki/Glossary#suffix-folding-or-tucking), but it seems odd that I would have left that in there.

We _could_ add `"TAOEUD/-G": "tiding"` and `"TAOEUD/-G/-S": "tidings"` to `condensed-strokes.json`, depending on the orthography rules. I'm wondering if it's worth creating a separate dictionary for that, such as `condensed-strokes-using-orthography-rules.json`. Perhaps that's unnecessary overhead and it's enough to leave a note in the commit message.

What do you think @paulfioravanti ?

**Comment by paulfioravanti** [comment]
I don't think I've got enough steno knowledge to determine what the pros and cons are of adding `"TAOEUD/-G": "tiding"` and `"TAOEUD/-G/-S": "tidings"` to `condensed-strokes.json` vs putting them in their own dictionary like `condensed-strokes-using-orthography-rules.json`.

Though, I guess the path of least resistance is to:

- add those two strokes to `condensed-strokes.json`
- change the entry in `top-10000-project-gutenberg-words.json` to `"TAOEUD/-G/-S": "tidings"`
- Make a note in the commit message that `"TAOEUD/-G": "tiding"` and `"TAOEUD/-G/-S": "tidings"` are added based on orthography rules (if you have any specific preferred wording, I'm happy to put that in)

**Comment by didoesdigital** [comment]
Sounds good to me. It's probably enough to mention "tiding" depends on the orthography rules because it changes "tide" to "tiding".
