### ISSUE TITLE
Dictionary entries for "march"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#12]
In some of the dictionaries, the `PHA*R` keystroke is used for lowercase "march" (walk in a military manner), but `PHA*R` actually outputs titleised "March" (the month):

https://github.com/didoesdigital/steno-dictionaries/blob/e0f8e572392cec1ce25277b318cb5d2316c43071/dictionaries/top-1000-words.json#L700

https://github.com/didoesdigital/steno-dictionaries/blob/e0f8e572392cec1ce25277b318cb5d2316c43071/dictionaries/top-10000-english-words.json#L493

https://github.com/didoesdigital/steno-dictionaries/blob/e0f8e572392cec1ce25277b318cb5d2316c43071/dictionaries/top-10000-project-gutenberg-words.json#L700

Is the entry for these dictionaries meant to be for the capitalised or lowercase version?

If lowercase, I'd propose a PR to change these entries to `"PHAFRPB": "march"`.
If uppercase, I'd propose a PR to change these entries to `"PHA*R": "March"`.

**Comment by didoesdigital** [comment]
Good catch @paulfioravanti! I've changed it to the lowercase version as it's more frequent and deployed the change. Thanks.
