### ISSUE TITLE
Issue with strokes for "arrive*"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#131]
In the current `dict.json` file, there are the following strokes for words containing "arrive", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"A/REUF": "arrive",
"A/RAEUF": "arrive",
"A/RAOEUF": "arrive",
"A/REUFD": "arrived",
"A/RAOEUFD": "arrived",
"A/RAOEUFS": "arrives",
"AE/RAOEUFD": "he arrived",
"AS/RAOEUF": "{^s arrive}",
```

In the `top-10000-project-gutenberg-words.json` dictionary, there is an entry for "arrive", that uses the following stroke:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L3126

Although Plover says it's a valid stroke, I feel that `"A/REUF": "arrive",` (and `"A/RAEUF": "arrive",` for that matter) could be mis-strokes, and that `"A/RAOEUF": "arrive",` with the elongated "ī" sound (`AOEU`) is a more accurate entry pronunciation-wise.

Given that there is only one entry for "arrives" (`"A/RAOEUFS": "arrives",`) which uses the elongated "ī" sound, as well as the `"AE/RAOEUFD": "he arrived",` and `"AS/RAOEUF": "{^s arrive}",` strokes, I would like to propose standardising on the elongated "ī" sound by:

- Removing the following entries from `dict.json`:
  - `"A/REUF": "arrive",`
  - `"A/RAEUF": "arrive",`
  - `"A/REUFD": "arrived",`
- Adding the following entries to `bad-habits.json`:
  - `"A/REUF": "arrive",`
  - `"A/RAEUF": "arrive",`
  - `"A/REUFD": "arrived",`
- Changing the stroke for "arrive" in `top-10000-project-gutenberg-words.json` from `A/REUF` to `A/RAOEUF`

**Comment by didoesdigital** [comment]
Thanks, @paulfioravanti.

As I mentioned in https://github.com/didoesdigital/steno-dictionaries/issues/103#issuecomment-581093631, a short "i" sound might be considered a brief. A useful example for reference is the pair of entries for `"HREUF": "live",` and `"HRAOEUF": "life",`. With that in mind, some people might see the "EU" entries as briefs as well as misstrokes, which might be worth mentioning in the commit. The "AEU" entry is much more likely to be considered a misstroke, missing the "O" in the elongated "ī" sound.

Your suggested changes all look good to me.
