### ISSUE TITLE
Issue with stroke for "pronounced"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#132]
In the current `dict.json` file, there are the following strokes for the word "pronounced", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PRO/TPHOUPBS/-D": "pronounced",
"PRO/TPHUPBS/-D": "pronounced",
"PROE/TPHOUPBS/-D": "pronounced",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "pronounced" is:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L2994

Although Plover says `"PRO/TPHUPBS/-D": "pronounced"` is a valid stroke, I feel that `"PRO/TPHOUPBS/-D": "pronounced"`, with the full "ow" (`OU`) sound, is a more accurate entry pronunciation-wise.

Given that all the entries in `dict.json` for "pronounce" use `OU`:

```json
"PRO/TPHOUPBS": "pronounce",
"PROE/TPHOUPBS": "pronounce",
"PROUPBS": "pronounce",
```

As well as the entry in `top-10000-project-gutenberg-words.json`:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L6808

I would like to propose:

- Removing `"PRO/TPHUPBS/-D": "pronounced",` from `dict.json`
- Adding `"PRO/TPHUPBS/-D": "pronounced",` to `bad-habits.json`
- Changing the "pronounced" entry in `top-10000-project-gutenberg-words.json` from `PRO/TPHUPBS/-D` to `PRO/TPHOUPBS/-D`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. Looks good to me. You might also remove `"PRO/TPHUPBS/KWRAEUGS": "pronunciation",` from `dict.json` and add it to `bad-habit.json`.
