### ISSUE TITLE
Issue with stroke for "protest"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#136]
In the current `dict.json` file, there are the following strokes for the word "protest", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PRO/TEFT": "protest",
"PROE/TEFT": "protest",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "protest" is:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L3718

Although I don't think I'd go so far as to suggest marking `"PRO/TEFT": "protest",` as a mis-stroke, I do feel that "PROE/TEFT": "protest", with the elongated "ō" is a more accurate stroke pronunciation-wise.

Given that the entry for "protested" in the `top-10000-project-gutenberg-words.json` dictionary uses the elongated "ō":

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L4199

I'd like to propose:

- Changing the `top-10000-project-gutenberg-words.json` entry for "protest" from `PRO/TEFT` to `PROE/TEFT`

**Comment by didoesdigital** [comment]
Thanks for the suggestion, @paulfioravanti. The entry `"PRO/TEFT": "protest",` uses the prefix entry, `"PRO": "{pro^}",`, which is relatively predictable and minimises the chances of word boundary errors. 

Despite the pronunciation, let's stick with the existing entry.

**Comment by paulfioravanti** [comment]
Thanks, @didoesdigital, the`"PRO": "{pro^}"` prefix didn't cross my mind at all when thinking about this stroke. Happy to close this out.
