### ISSUE TITLE
Issue with stroke for "infant"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#137]
In the current `dict.json` file, there are the following strokes for the word "infant", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EUPB/TPAPBT": "infant",
"EUPB/TPAPT": "infant",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "infant" is:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L4055

Although Plover says `"EUPB/TPAPT": "infant"` is a valid stroke, I feel that `"EUPB/TPAPBT": "infant"` with the full "n" (`PB`) sound, is a more accurate entry.

Given that all the other dictionary entries in `dict.json` that contain "infant" in their word use the full `PB` stroke:

```json
"EUPB/TPAPB/TAOEUL": "infantile",
"EUPB/TPAPB/TAOEUL/PRAL/SEUS": "infantile paralysis",
"EUPB/TPAPB/TEU/SAO*EUD": "infanticide",
"EUPB/TPAPB/TEU/SAOEUD": "infanticide",
"EUPB/TPAPB/TREU": "infantry",
"EUPB/TPAPB/TREU/PHEPB": "infantrymen",
"EUPB/TPAPBT": "infant",
"EUPB/TPAPBT/HRAOEUZ": "infantilize",
"EUPB/TPAPBT/HRAOEUZ/-D": "infantilized",
"EUPB/TPAPBT/KRAOEUD": "infanticide",
"EUPB/TPAPBT/REU": "infantry",
"EUPB/TPAPBT/SAO*EUD": "infanticide",
"EUPB/TPAPBT/SAOEUD": "infanticide",
"EUPB/TPAPBTS": "infants",
```

I'd like to propose:

- Removing `"EUPB/TPAPT": "infant",` from `dict.json`
- Adding `"EUPB/TPAPT": "infant",` to `bad-habits.json`
- Changing the `top-10000-project-gutenberg-words.json` entry for "infant" from `EUPB/TPAPT` to `EUPB/TPAPBT`

**Comment by didoesdigital** [comment]
Nailed it, @paulfioravanti.
