### ISSUE TITLE
Issue with strokes for "encourage*"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#145]
In the current `dict.json` file, there are the following strokes for the words that contain "encourage", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EPB/KORPBG": "encourage",
"EPB/KORPBL": "encourage",
"EPB/KORPBLG": "encourage",
"EPB/KURPBLG": "encourage",
"EPB/TKORPBLG": "encourage",
"EPB/KORBLG/-D": "encouraged",
"EPB/KORPBLGD": "encouraged",
"EPB/KURPBLGD": "encouraged",
"EPB/KORPBLGS": "encourages",
"EPB/KURPBLGS": "encourages",
"EPB/KORPBLG/*PLT": "encouragement",
"EPB/KORPLT": "encouragement",
"EPB/KURPBLG/*PLT": "encouragement",
"EUPB/KORPBLG/*PLT": "encouragement",
"TKPWEUF/EPB/KORPLT": "give encouragement",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "encourage" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L4343

While in n the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "encouragement" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L4912

The majority of the entries here would seem to use the full `PBLG` for the "j" sound in "courage", which is what I would expect for the stroke. So, could all the strokes that remove a letter from the `PBLG` combination be considered mis-strokes?

If so, then I'd like to propose:

- Removing the following entries from `dict.json`, and adding them to `bad-habits.json`
  - `"EPB/KORPBG": "encourage",`
  - `"EPB/KORPBL": "encourage",`
  - `"EPB/KORBLG/-D": "encouraged",`
- Changing the "encourage" entry in `top-10000-project-gutenberg-words.json` from `EPB/KORPBG` to `EPB/KORPBLG`

I'm not 100% sure about the strokes for "encouragement" that I would potentially mark as mis-strokes:

- `"EPB/KORPLT": "encouragement",`
- `"TKPWEUF/EPB/KORPLT": "give encouragement",`

If, say, the `PL` here is meant to be read as an "m", then the stroke reads fine to me (though perhaps this could conflict with how the `"EPB/KORPBLG/*PLT": "encouragement"` is meant to be read...?), and so no action would be needed. If not, and all "encourage"-based words should standardise around the "j" sound, then I'd propose:

- Removing the following entries from `dict.json`, and adding them to `bad-habits.json`
  - `"EPB/KORPLT": "encouragement",`
  - `"TKPWEUF/EPB/KORPLT": "give encouragement",`
- Changing the "encouragement" entry in `top-10000-project-gutenberg-words.json` from `EPB/KORPLT` to `EPB/KORPBLGT`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. The entries for "encourage" all look good to me.

Seeing an entry like `"TKPWEUF/EPB/KORPLT": "give encouragement",` usually suggests to me that it's been specifically added to avoid a word boundary error ("given conformant") with the main stroke that's usually used for the word (e.g. `EPB/KORPLT` for "encouragement"). Here though, it's not using the brief for "given", the suffix `"*EPB": "{^en}",` or the full `PBLG` for the "g" sound.

For consistency with "courage" and "encourage", it would be nice to use the full `PBLG` in "encouragement".

I think this is "brief or misstroke" territory. On the balance, for teaching beginner stenographers, I think it's worth:

- Removing the following entries from `dict.json`, and adding them to `bad-habits.json`
    - `"EPB/KORPLT": "encouragement",`
    - `"TKPWEUF/EPB/KORPLT": "give encouragement",`
- Changing the "encouragement" entry in `top-10000-project-gutenberg-words.json` from `EPB/KORPLT` to `EPB/KORPBLGT`

**Comment by didoesdigital** [comment]
Sorry, @paulfioravanti , I should have said the _changes_ for “encourage” all look good to me. Are you happy to add them to your PR?

- Removing the following entries from dict.json, and adding them to bad-habits.json
    - `"EPB/KORPBG": "encourage",`
    - `"EPB/KORPBL": "encourage",`
    - `"EPB/KORBLG/-D": "encouraged",`
- Changing the "encourage" entry in `top-10000-project-gutenberg-words.json` from `EPB/KORPBG` to `EPB/KORPBLG`

**Comment by paulfioravanti** [comment]
Thanks for the clarification, @didoesdigital. Done!
