### ISSUE TITLE
Issue with stroke for "induce"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#146]
In the current `dict.json` file, there are the following strokes for the word "induce", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EUP/TKAOUS": "induce",
"EUPB/TKAOES": "induce",
"EUPB/TKAOUGS": "induce",
"EUPB/TKAOUS": "induce",
"EUPB/TKAUS": "induce",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "induce" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L4358

Although Plover says `"EUPB/TKAUS": "induce"` and `"EUPB/TKAOES": "induce"` are valid strokes, I feel that strokes with the elongated "ū", like `"EUPB/TKAOUS": "induce"`, are more accurate entries pronunciation-wise.

Given that:

All other entries that contain "induce" use `AOU`:

```json
"EUPB/TKAOUFD": "induced",
"EUPB/TKAOUFS": "induces",
"EUPB/TKAOUPLT": "inducement",
"EUPB/TKAOURS": "inducer",
"EUPB/TKAOUS/*PLT": "inducement",
"EUPB/TKAOUS/-D": "induced",
"EUPB/TKAOUS/-PLTS": "inducements",
"EUPB/TKAOUS/ER": "inducer",
```

Also, the stroke for "induced" in `top-10000-project-gutenberg-words.json` uses `AOU`:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L3213

I would like to propose:

- Removing the following strokes from `dict.json`
  - `"EUPB/TKAOES": "induce",`
  - `"EUPB/TKAUS": "induce",`
  - (maybe also `"EUP/TKAOUS": "induce",` since it drops the `B` key for the "n" stroke...?)
- Adding the following strokes to `bad-habits.json`
  - `"EUPB/TKAOES": "induce",`
  - `"EUPB/TKAUS": "induce",`
  - (maybe also `"EUP/TKAOUS": "induce",`...?)
- Changing the "induce" entry in `top-10000-project-gutenberg-words.json` from `EUPB/TKAUS` to `EUPB/TKAOUS`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. That all looks good to me, including moving the misstrokes missing the `B` key in `EUPB/` for "in^".

**Comment by didoesdigital** [comment]
I'll fix these in a related commit.
