### ISSUE TITLE
Issue with stroke for "conclude"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#147]
In the current `dict.json` file, there are the following strokes for the word "conclude", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"KAUPB/HRAOUD": "conclude",
"KAUPB/KHRAOUD": "conclude",
"KOPB/KHRAOUD": "conclude",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "conclude" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L4364

Plover itself has the following strokes for "conclude":

```
conclude:
   KAUPB/HRAOUD
   KAUPB/KHAOUD
   KOPB/KHRAOUD
   KAUPB/KHRAOUD
   KAUPB/TKHRAOUD
```

So, currently, the dictionaries do not currently have the following entries:

```json
"KAUPB/KHAOUD": "conclude",
"KAUPB/TKHRAOUD": "conclude",
```

To be honest, neither of these strokes look quite right to me, but since that's subjective, is it worth adding them either to `dict.json`, or perhaps directly to `bad-habits.json` if you think they also don't look quite right?

Anyway, although Plover says `"KAUPB/HRAOUD": "conclude"` is a valid stroke, since it's missing the `K` before `HR` for the "cl" sound, it looks potentially like a mis-stroke to me, and `"KAUPB/KHRAOUD": "conclude"` looks more accurate pronunciation-wise.

Given that:

All other entries that have strokes for words that contain "conclude" use the `K`:

```json
"KAUPB/KHRAOUDZ": "concludes",
"KOPB/KHRAOUD": "conclude",
"KOPB/KHRAOUDZ": "concludes",
```

I would like to propose:

- Removing `"KAUPB/HRAOUD": "conclude"` from `dict.json`
- Adding `"KAUPB/HRAOUD": "conclude"` to `bad-habits.json`
- Changing the "conclude" entry in `top-10000-project-gutenberg-words.json` from `KAUPB/HRAOUD` to `KAUPB/KHRAOUD`

By the by, if these proposals are agreed, then perhaps the `top-10000-project-gutenberg-words.json` for "concluded":

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L2285

could also be changed to, perhaps, `KAUPB/KHRAOUD/-D`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti 

Moving these straight to `bad-habits.json` sounds good:

```
"KAUPB/KHAOUD": "conclude",
"KAUPB/TKHRAOUD": "conclude",
```

These also look good:

- Removing` "KAUPB/HRAOUD": "conclude"` from `dict.json`
- Adding `"KAUPB/HRAOUD": "conclude"` to `bad-habits.json`
- Changing the "conclude" entry in `top-10000-project-gutenberg-words.json` from `KAUPB/HRAOUD` to `KAUPB/KHRAOUD`

Let's also add `"KAUPB/KHRAOUD/-D": "concluded",` to `condensed-strokes.json` and update "concluded" in `top-10000-project-gutenberg-words.json`
