### ISSUE TITLE
Issue with stroke for "intentions"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#148]
In the current `dict.json` file, there are the following strokes for the word "intentions", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EUPB/TEPBGS/-S": "intentions",
"EUPB/TEPGS/-S": "intentions",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "intentions" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L4350

Although Plover says `"EUPB/TEPGS/-S": "intentions"` is a valid stroke, since it's missing the `B` for the "n" sound of `PB`, it looks potentially like a mis-stroke to me, and `"EUPB/TEPBGS/-S": "intentions"` looks more accurate pronunciation-wise.

Given that:

Nearly all other entries that have 2 or more strokes for words that contain "intention" use the `PB` for "n":

```json
"EUPB/TEPBGS/-S": "intentions",
"EUPB/TEPBGS/AL": "intentional",
"EUPB/TEPBGS/HREU": "intentionally",
"EUPB/TEPBGS/KWA*L": "intentional",
"EUPB/TEPBGS/KWRA*L": "intentional",
"EUPB/TEPBL": "intentional",
"EUPB/TEPBL/A*L": "intentional",
"SPWEPBGS/HREU": "intentionally",
"WEL/EUPB/TEPBGS/-D": "well-intentioned",
```

I would like to propose:

- Removing `"EUPB/TEPGS/-S": "intentions"` from `dict.json`
- Adding `"EUPB/TEPGS/-S": "intentions"` to `bad-habits.json`
- Changing the "intentions" entry in `top-10000-project-gutenberg-words.json` from `EUPB/TEPGS/-S` to `EUPB/TEPBGS/-S`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. Looks Good To Me.
