### ISSUE TITLE
Issue with stroke for "impressions"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#149]
In the current `dict.json` file, there are the following strokes for the word "impressions", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EUPL/PREG/-S": "impressions",
"EUPL/PREGS/-S": "impressions",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "impressions" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L4501

Although Plover says `"EUPL/PREG/-S": "impressions"` is a valid stroke, since it's missing the `S` after `G` for the "shun" sound, it looks potentially like a mis-stroke to me, and `"EUPL/PREGS/-S": "impressions"` looks more accurate pronunciation-wise.

Given that:

Nearly all other entries that contain "impression" use the `GS` stroke for "shun":

```json
"EUPL/PREGS": "impression",
"EUPL/PREGS/-BL": "impressionable",
"EUPL/PREGS/EUFPL": "Impressionism",
"EUPL/PREGS/EUFT": "Impressionist",
"EUPL/PREGS/PWHREU": "impressionably",
"EUPL/PWREGS": "impression",
"POEFT/EUPL/PREGS/EUFPL": "Post-Impressionism",
"TPHAOE/EUPL/PREGS": "neo-impression",
"TPHAOE/KWRO/EUPL/PREGS": "neo-impression",
"TPHAOE/KWRO/EUPL/PREGS/*EUS/EUBG": "neo-impressionistic",
"TPHAOE/KWRO/EUPL/PREGS/EUFPL": "neo-impressionism",
"TPHAOE/KWRO/EUPL/PREGS/EUS/TEUBG": "neo-impressionistic",
```

and also that the entry for "impression" in `top-10000-project-gutenberg-words.json` also uses `GS` for "shun":

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L1557

I would like to propose:

- Removing `"EUPL/PREG/-S": "impressions"` from `dict.json`
- Adding `"EUPL/PREG/-S": "impressions"` to `bad-habits.json`
- Changing the "impressions" entry in `top-10000-project-gutenberg-words.json` from `EUPL/PREG/-S` to `EUPL/PREGS/-S`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. That all sounds good to me.
