### ISSUE TITLE
Issue with stroke for "reverse"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#150]
In the current `dict.json` file, there are the following strokes for the word "reverse", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"RAOE/SRERS": "reverse",
"RE/SERS": "reverse",
"RE/SRERS": "reverse",
"RE/SRES": "reverse",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "reverse" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L5420

I don't think I would go so far as to say that any of these strokes look like a mis-stroke, but I think that `"RE/SRERS": "reverse"` looks like more accurate entry pronunciation-wise than `"RE/SRES": "reverse"`, and hence I would like to propose to:

- Change the "reverse" entry in `top-10000-project-gutenberg-words.json` from `RE/SRES` to `RE/SRERS`
- Add a `"R*EFRS": "reverse"` entry to `dict.json` (this stroke is in Plover but not contained in the dictionaries at all)

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. If we add `"R*EFRS": "reverse"` to `dict.json`, let's also change the `top-10000-project-gutenberg-words.json` entry to use that new brief.
