### ISSUE TITLE
Issue with stroke for "indulgence"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#151]
In the current `dict.json` file, there are the following strokes for the word "indulgence", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EUPB/TKUL/SKWREPBS": "indulgence",
"EUPB/TKULG/EPBS": "indulgence",
"EUPB/TKULS/EPBS": "indulgence",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "indulgence" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L5756

I'm not sure any of the entries look like a mis-stroke, but I think that `"EUPB/TKULG/EPBS": "indulgence"`, with the `LG` "lj" sound, looks like more accurate entry pronunciation-wise than the current `"EUPB/TKULS/EPBS": "indulgence"` (I would be inclined to consider this a mis-stroke), in `top-10000-project-gutenberg-words.json`. So, I would like to propose to:

- Change the "indulgence" entry in `top-10000-project-gutenberg-words.json` from `EUPB/TKULS/EPBS` to `EUPB/TKULG/EPBS`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. That sounds good to me. I'm also happy to consider `"EUPB/TKULS/EPBS": "indulgence"` a misstroke, hitting the `S` key instead of the `G` in the `LG` group for "lj" sounds. Let's move that from `dict.json` to `bad-habits.json`.
