### ISSUE TITLE
Issue with stroke for "overwhelmed"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#152]
In the current `dict.json` file, there are the following strokes for the word "overwhelmed", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"AUFR/KHEPLD": "overwhelmed",
"AUFR/WHEL/PH-D": "overwhelmed",
"AUFR/WHEPL/-D": "overwhelmed",
"AUFR/WHEPLD": "overwhelmed",
"O*FR/WHEL/-PLD": "overwhelmed",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "overwhelmed" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L5829

I couldn't find reference any reference for the `KH` stroke as a "wh" sound, and given that `AUFR/KHEPLD` is the only one of the set that uses it, I'm inclined to think of it as a mis-stroke, but I'm not sure. At the very least, though, I think that `"AUFR/WHEPLD": "overwhelmed"` is a better entry pronunciation-wise than `"AUFR/KHEPLD": "overwhelmed"`, and so would like to at least propose:

- Change the "overwhelmed" entry in `top-10000-project-gutenberg-words.json` from `AUFR/KHEPLD` to `AUFR/WHEPLD`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. Your proposal sounds good. `"AUFR/KHEPLD": "overwhelmed",` looks like a misstroke hitting the `K` instead of the `W` key (a common misstroke for people), so let's move it to `bad-habits.json`.
