### ISSUE TITLE
Issue with strokes for "okay"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#153]
In the current `dict.json` file, there are the following strokes for the word "okay":

```json
"O*EBG": "okay",
"O/KAEU": "okay",
"OBLG": "okay",
"OE/KAEU": "okay",
```

The final three strokes in this list are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), but `"O*EBG": "okay"` now outputs to "ok":

Plover also lists the stroke `"OBG": "okay"`, but the dictionaries have this listed as a mis-stroke...

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/misstrokes.json#L1256

...which would seem to be the result of [this commit](https://github.com/didoesdigital/steno-dictionaries/commit/496c60f01247c3a4e0cb59d2894c2187279cfdd4).

In the `top-200-words-spoken-on-tv.json` dictionary, the stroke used for "okay" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-200-words-spoken-on-tv.json#L78

To me, `"OBG": "okay"` looks like a more accurate stroke than `"OBLG": "okay"`, but I'm wagering that the fact that it's been marked as a mis-stroke means there's probably some orthographic rule that I don't know about that I wasn't able to ascertain from the commit linked previously.

So, would it be possible to request an explanation as to why `"OBG": "okay"` is a mis-stroke?

Also, I'd like to propose:

- Changing `"O*EBG": "okay"` in `dict.json` to `"O*EBG": "ok"`

**Comment by didoesdigital** [comment]
Thanks for putting this together, @paulfioravanti. Digging further, I ran `git log -S'"OBG": "okay",' -- dict.json --follow-parent` to find 5653e72e2157a84fc88502bca5eb19989f3672b3, which seems to be a matter of preference to use `OBG` for "ok" and `O*EBG` for okay. Without a detailed explanation, I would guess my thought process was `O` exactly matches "o" and `BG` exactly matches "k" so `OBG` should be "ok" and the version with the asterisk should be the longer word.

`"OBLG": "okay",` looks to me like a misstroke, incorrectly adding a stray `L`.

Given Plover's dictionary has strokes like:

```
"OBGD": "okayed",
"OBG/-S": "okays",
```

… where "okay" uses the `OBG` format, let's do the following:

- Add `"O*EBG": "ok",` to `dict.json`
- Add `"OBG": "okay",` to `dict.json`
- Remove `"OBLG": "okay",` from `dict.json`
- Change the entry in `top-200-words-spoken-on-tv.json` from `"OBLG": "okay",` to `"OBG": "okay",`

Does that sound right? If so, I can make these changes.

**Comment by paulfioravanti** [comment]
@didoesdigital that course of action looks good to me! Happy for you to make those changes. Also, TIL git's `--follow-parent` flag. Thanks!
