### ISSUE TITLE
Issue with two-stroke entries for "uncertainty"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#154]
In the current `dict.json` file, there are the following strokes for the word "uncertainty", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"UPB/SERPBLT": "uncertainty",
"UPB/SERPBT": "uncertainty",
"UPB/SERPBT/TEU": "uncertainty",
"UPB/SERPT": "uncertainty",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "uncertainty" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L6046

Out of the 3 two-stroke entries, only `"UPB/SERPBT": "uncertainty"` seems correct to me pronunciation-wise, with `"UPB/SERPT": "uncertainty"` missing `B` for the "n" sound, and `"UPB/SERPBLT": "uncertainty"` containing an un-needed(?) `L`.

I'm not sure if I'd mark them as mis-strokes, but at the very least, given that the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "uncertain" is:

https://github.com/didoesdigital/steno-dictionaries/blob/50407b89a3c2e928d04f8f7c3687513e273962be/dictionaries/top-10000-project-gutenberg-words.json#L3322

I'd like to propose:

- Changing the "uncertainty" entry in `top-10000-project-gutenberg-words.json` from `UPB/SERPT` to `UPB/SERPBT` so that they match up

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti.

`"UPB/SERPT": "uncertainty"` looks like a misstroke, missing the `B` key in the "n" sound.

`"UPB/SERPBLT": "uncertainty",` looks like a misstroke, adding a stray `L` key.

Let's move those from `dict.json` to `bad-habits.json` and change the "uncertainty" entry in `top-10000-project-gutenberg-words.json` from `UPB/SERPT` to `UPB/SERPBT`.
