### ISSUE TITLE
Issue with strokes for "enchant*"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#165]
In the current `dict.json` file, there are the following strokes for "enchant", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EPB/HAPBT": "enchant",
"EPB/KHAPBT": "enchant",
```

The word "enchant" is not used in the `top-10000-project-gutenberg-words.json` dictionary, but there is a stroke used for "enchanted" in it:

https://github.com/didoesdigital/steno-dictionaries/blob/28e712f6d2e31b61a87448b1f6e121fe487f1e91/dictionaries/top-10000-project-gutenberg-words.json#L6970

`EPB/HAPBT` for "enchant" looks to me like a mis-stroke as it's missing the `K` for the "ch" sound.

Given that all the other entries for words that contain "enchant" in the dictionaries use the `KH` stroke:

**`dict.json`**

```json
"EPB/KHAPBT/*PLT": "enchantment",
"EPB/KHAPBT/-G": "enchanting",
"EPB/KHAPBT/RES": "enchantress",
"EPB/KHAPBT/TRES": "enchantress",
"EPB/KHAPLT": "enchantment",
```

https://github.com/didoesdigital/steno-dictionaries/blob/28e712f6d2e31b61a87448b1f6e121fe487f1e91/dictionaries/top-10000-project-gutenberg-words.json#L9511
https://github.com/didoesdigital/steno-dictionaries/blob/28e712f6d2e31b61a87448b1f6e121fe487f1e91/dictionaries/top-10000-project-gutenberg-words.json#L9990

I would like to propose:

- Removing `"EPB/HAPBT": "enchant"` from `dict.json`
- Adding `"EPB/HAPBT": "enchant"` to `bad-habits.json`
- Changing the "enchanted" entry in `top-10000-project-gutenberg-words.json` from `EPB/HAPBT/-D` to `EPB/KHAPBT/-D`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. That all sounds good to me. Let's also add a new stroke to `condensed-strokes.json` for “enchanted” using `EPB/KHAPBT/-D`.
