### ISSUE TITLE
Issue with stroke for "reluctant*"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#166]
In the current `dict.json` file, there are the following strokes for the words that contain "reluctant", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"RAOE/HRUBG/TAPBT": "reluctant",
"RAOE/HRUBGT/APBT/HREU": "reluctantly",
"RE/HRUBG/TAPBT": "reluctant",
"RE/HRUBG/TAPBT/HREU": "reluctantly",
"RE/HRUBGT/APBT": "reluctant",
"RE/HRUBGT/APBT/HREU": "reluctantly",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the strokes used for "reluctant" and "reluctantly" are:

https://github.com/didoesdigital/steno-dictionaries/blob/28e712f6d2e31b61a87448b1f6e121fe487f1e91/dictionaries/top-10000-project-gutenberg-words.json#L7628

https://github.com/didoesdigital/steno-dictionaries/blob/28e712f6d2e31b61a87448b1f6e121fe487f1e91/dictionaries/top-10000-project-gutenberg-words.json#L7031

While I'm not sure I can make the case that any of the entries in `dict.json` are mis-strokes, I'd like to make the case that `"RE/HRUBG/TAPBT": "reluctant"` is a better stroke for beginners to use in Typey-Type due to:

1. It better matches the natural syllables of the word: "re-luc-tant" vs "re-luct-ant
2. The Plover display during intermediate strokes during creation of the word make more sense:
    - `RE/HRUBGT/APBT` => re -> reHRUBGT -> reluctant
    - `RE/HRUBG/TAPBT`  => re -> reluck -> reluctant

Therefore, I'd like to propose:

- Changing the "reluctant" entry in `top-10000-project-gutenberg-words.json` from `RE/HRUBGT/APBT` to `RE/HRUBG/TAPBT`
- Changing the "reluctantly" entry in `top-10000-project-gutenberg-words.json` from `RE/HRUBGT/APBT/HREU` to `RE/HRUBG/TAPBT/HREU`

**Comment by didoesdigital** [comment]
Thanks for writing this up, @paulfioravanti. That makes sense and I appreciate how you're thinking about the experience for beginners learning steno through Typey Type.

There exists a suffix entry, `"APBT": "{^ant}",` while there's no suffix entry for ^tant, so between those two entries I'd prefer to encourage the correct suffix usage and stick with `"RE/HRUBGT/APBT": "reluctant",`. That would also mean keeping `"RE/HRUBGT/APBT/HREU": "reluctantly",`

**Comment by paulfioravanti** [comment]
Thanks for the explanation, @didoesdigital. I didn't even think about suffix use. Given the desire to encourage correct suffix usage, I can agree that these strokes should stay as-is.
