### ISSUE TITLE
Issue with strokes for "adore*"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#167]
In the current `dict.json` file, there are the following strokes for the word "adore", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"A/KOR": "adore",
"A/TKOER": "adore",
"A/TKOR": "adore",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the strokes used for "adore" and "adored" are:

https://github.com/didoesdigital/steno-dictionaries/blob/28e712f6d2e31b61a87448b1f6e121fe487f1e91/dictionaries/top-10000-project-gutenberg-words.json#L8141

https://github.com/didoesdigital/steno-dictionaries/blob/28e712f6d2e31b61a87448b1f6e121fe487f1e91/dictionaries/top-10000-project-gutenberg-words.json#L7076

`"A/KOR": "adore"` looks like a mis-stroke to me due to the lack of a `T` stroke in `TK` for the "d" sound. `"A/TKOER": "adore",` also looks a bit strange to me with the elongated "ō" vowel, but I'm guessing that it's there as perhaps some kind of inversion since "adore" ends with an "e"(...?)

Anyway, I'd like to at least propose:

- Removing `"A/KOR": "adore"` from `dict.json`
- Adding `"A/KOR": "adore"` to `bad-habits.json`
- Changing the "adore" entry in `top-10000-project-gutenberg-words.json` from `A/KOR` to `A/TKOR`
- Changing the "adored" entry in `top-10000-project-gutenberg-words.json` from `A/KOR/-D` to `A/TKOR/-D`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. Yes, `"A/KOR": "adore"` looks like a misstroke missing `T` in `TK`. Your suggestions all look good.

Regarding `OER` vs `OR`, I'm not sure about the thinking there.

- [The Art of Chording suggests the `OER` version is reserved for briefs.](https://www.artofchording.com/sounds/oh.html#but-there-s-a-catch).
- [Learn, Plover! suggests "If the vowel letter in the written word appears without another vowel letter next to it, then it doesn't matter which short vowel sound it makes. The Plover key labeled with that letter is always used to stroke the word."](https://sites.google.com/site/learnplover/lesson-1-fingers-and-keys#TOC-Rules-For-Short-Vowel-Sounds)

I don't know words with "ore" are pronounced differently in different variants of English.

I can find examples of both `OER` and `OR` for "-ore" words for single-stroke briefs as well as multi-stroke words. `OER` examples:

```
"WHOER": "whore",
"KHOER": "chore",
"KWROER": "yore",
"POER": "pore",
"SHOER": "shore",
"EUG/TPHOER": "ignore",
"EUPL/PHROER": "implore",
"A/TPOER": "afore",
"EPB/KOER": "encore",
"EBGS/PHROER": "explore",
"AUF/SHOER": "offshore",
```

`OR` examples:

```
"STOR": "store",
"SOR": "sore",
"SKOR": "score",
"PHOR": "more",
"HROR": "lore",
"THAOE/TKOR": "Theodore",
"PWAOBG/STOR": "bookstore",
"TKE/PHROR": "deplore",
"TKPWA/HROR": "galore",
"UPBD/SKOR": "underscore",
```

I suspect it probably comes down to avoid conflicts on a case-by-case basis.

I'm happy to stick with the shorter one wherever it doesn't have conflicts.
