### ISSUE TITLE
Issue with strokes for "incessant*"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#168]
In the current `dict.json` file, there are the following strokes for the word "incessant", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EUPB/SEFPBT": "incessant",
"EUPB/SEPBT": "incessant",
"EUPB/SES/APBT": "incessant",
"EUPB/SES/SAPBT": "incessant",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the strokes used for "incessant" and "incessantly" are:

https://github.com/didoesdigital/steno-dictionaries/blob/28e712f6d2e31b61a87448b1f6e121fe487f1e91/dictionaries/top-10000-project-gutenberg-words.json#L7073

https://github.com/didoesdigital/steno-dictionaries/blob/28e712f6d2e31b61a87448b1f6e121fe487f1e91/dictionaries/top-10000-project-gutenberg-words.json#L7450

I don't think I'd go so far as to say `"EUPB/SEPBT": "incessant"` looks like a mis-stroke (since there's no English word like "insent" that it could clash with and it does sound like a proper abbreviation of "incessant"), but `"EUPB/SEFPBT": "incessant"`, with the added `F` for "incessant"'s "s" sound seems like a more accurate stroke to me.

So, I'd like to propose:

- Changing the "incessant" entry in `top-10000-project-gutenberg-words.json` from `EUPB/SEPBT` to `EUPB/SEFPBT`
- Changing the "incessantly" entry in `top-10000-project-gutenberg-words.json` from `EUPB/SEPBT/HREU` to `EUPB/SEFPBT/HREU`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. Nice to see these kinds of improvements for beginners.

Thinking out loud, I don't think it matters that `SEFPBT` is "seventy" or that `SEPBT` is "sent" here.

I don't have any strong feelings on the `"EUPB/SEFPBT": "incessant",` vs `"EUPB/SEPBT": "incessant",`, so your changes sound fine to me.

We could also add `"EUPB/SEPBT/HREU": "incessantly", ` to `condensed-strokes.json` as an alternative.
