### ISSUE TITLE
Issue with stroke for "inscribe"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#172]
In the current `dict.json` file, there are the following strokes for "inscribe", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EUPB/KRAOEUB": "inscribe",
"EUPB/SKRAOEUB": "inscribe",
```

The word "inscribe" is not used in the `top-10000-project-gutenberg-words.json` dictionary, but there is a stroke used for "inscribed" in it:

https://github.com/didoesdigital/steno-dictionaries/blob/cdcf87902e2859a535b8f469968522a9a0cb3468/dictionaries/top-10000-project-gutenberg-words.json#L8009

`"EUPB/KRAOEUB": "inscribe"` looks like a mis-stroke to me, as it's missing the `S` in "in**s**cribe". So, I would like to propose:

- Removing `"EUPB/KRAOEUB": "inscribe"` from `dict.json`
- Adding `"EUPB/KRAOEUB": "inscribe"` to `bad-habits.json` (or `condensed-strokes.json`?)
- Changing the "inscribed" entry in `top-10000-project-gutenberg-words.json` from `EUPB/KRAOEUB/-D` to `EUPB/SKRAOEUB/-D`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti, looks good to me!

**Comment by paulfioravanti** [comment]
Thanks @didoesdigital!

With regards to the following point:

> Adding `"EUPB/KRAOEUB": "inscribe"` to `bad-habits.json` (or `condensed-strokes.json`?)

I'm assuming that putting `"EUPB/KRAOEUB": "inscribe"` into `bad-habits.json` is the course of action, and not into `condensed-strokes.json`.

**Comment by didoesdigital** [comment]
Yep, add `"EUPB/KRAOEUB": "inscribe"` to `bad-habits.json` because it's a misstroke missing the `S` key. Thanks @paulfioravanti, for flagging the need for more clarity there.
