### ISSUE TITLE
Stroke for "impracticable" outputs to "impracticallable"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#182]
In the current `dict.json` and `noun.json` file, there is the following stroke for "impracticable":

```json
"EUPL/PRABGT/-BL": "impracticable"
```

The word "impracticable" doesn't have an entry in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), and, unfortunately, the `EUPL/PRABGT/-BL` stroke as-is ends up translating to "impracticallable".

However, I did find (by trial and error) that the stroke `EUPL/PRA*BGT/-BL` _does_ translate to "impracticable", so I would like to propose:

- Changing the `"EUPL/PRABGT/-BL": "impracticable"` entries in `dict.json` and `nouns.json` to `"EUPL/PRA*BGT/-BL": "impracticable"`

**Comment by didoesdigital** [comment]
Thanks for wrangling that @paulfioravanti . 

There exists an entry for `"PRABGT/EUBG/-BL": "practicable",`

Using the prefix `"EUPL": "{im^}",` and these suffixes `"EUBG": "{^ic}",` and `"-BL": "{^able}",` we could make an entry for  `"EUPL/PRABGT/EUBG/-BL": "impracticable",` that leans on more existing prefix and suffix conventions.

Let's:

- remove the entry from `nouns.json`
- add `"EUPL/PRABGT/EUBG/-BL": "impracticable",` to `condensed-strokes.json` 
- update the outline for 'impracticable' in `top-10000-project-gutenberg-words.json` to  `"EUPL/PRABGT/EUBG/-BL": "impracticable",`
