### ISSUE TITLE
Stroke for "installed" has long "ā" sound and missing a `D` ending.

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#183]
In the current `dict.json` file, there are the following strokes for "install", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EUPB/STAEUL": "installed",
"EUPB/STAL/-D": "installed",
"EUPB/STAULD": "installed",
"EUPB/STAULT": "installed",
"EUPB/STKAULD": "installed",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "installed" is:

https://github.com/didoesdigital/steno-dictionaries/blob/c7dc49d11ee6b88122e0ea12b5c18541c155dc3d/dictionaries/top-10000-project-gutenberg-words.json#L8926

`"EUPB/STAEUL": "installed"` looks like a mis-stroke to me, as the long `AEU` vowel doesn't sound right for the word, and it's missing a `D` ending. For a two-stroke entry, `"EUPB/STAULD": "installed"` seems like a more appropriate choice. So, I would like to propose:

- Removing `"EUPB/STAEUL": "installed",` from `dict.json`
- Adding `"EUPB/STAEUL": "installed","` to `bad-habits.json`
- Changing the "installed" entry in `top-10000-project-gutenberg-words.json` from `EUPB/STAEUL` to `EUPB/STAULD`

I would also consider offering up `"EUPB/STAULT": "installed"` as a mis-stroke candidate due to the `T` ending. I'm wagering it's there to offer an option so that you don't have to reach for the `D` key(?), but regardless, it doesn't look quite right to me, personally.

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti !

Let's do as you recommended:

- Removing `"EUPB/STAEUL": "installed",` from `dict.json`
- Adding `"EUPB/STAEUL": "installed",` to `bad-habits.json`
- Changing the "installed" entry in `top-10000-project-gutenberg-words.json` from `EUPB/STAEUL` to `EUPB/STAULD`
- Move `"EUPB/STAULT": "installed"` to `bad-habits.json`
