### ISSUE TITLE
Issue with stroke for "descendant"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#184]
In the current `dict.json` file, there are the following strokes for "descendant", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"TKE/SEPB/TKAPBT": "descendant",
"TKE/SEPBT/APBT": "descendant",
"TKE/SKEPBD/APBT": "descendant",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "descendant" is:

https://github.com/didoesdigital/steno-dictionaries/blob/c7dc49d11ee6b88122e0ea12b5c18541c155dc3d/dictionaries/top-10000-project-gutenberg-words.json#L9021

I'm not sure whether I'd go so far as to say any of these strokes look like a mis-stroke, but, to me at least, `"TKE/SEPB/TKAPBT": "descendant"` sounds the closest phonetically, and so I would like to propose just:

- Changing the "descendant" entry in `top-10000-project-gutenberg-words.json` from `TKE/SEPBT/APBT` to `TKE/SEPB/TKAPBT`

**Comment by didoesdigital** [comment]
There exists a suffix entry `"APBT": "{^ant}",` so I'd prefer to stick with one of the entries that uses that. Alternatively, we might add a `condensed-strokes.json` entry for `"TKE/SEPBD/APBT": "descendant",` using the existing suffix entry and existing entry for `"TKE/SEPBD": "descend",`

**Comment by paulfioravanti** [comment]
Adding `"TKE/SEPBD/APBT": "descendant"` to `condensed-strokes.json` sounds good to me.
