### ISSUE TITLE
Stroke for "logic" missing `G` stroke for "j" sound

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#185]
In the current `dict.json` file, there are the following strokes for "logic", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"HROPBL/EUBG": "logic"
"HROPBLG/EUBG": "logic"
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "logic" is:

https://github.com/didoesdigital/steno-dictionaries/blob/2896e5f70fdfe006afc1924aad07079e18ad1a8e/dictionaries/top-10000-project-gutenberg-words.json#L6081

`"HROPBL/EUBG": "logic"` looks like a mis-stroke to me, as it is missing the `G` stroke to make the full `PBLG` "j" sound. So, I would like to propose:

- Removing `"HROPBL/EUBG": "logic"` from `dict.json`
- Adding `"HROPBL/EUBG": "logic"` to `bad-habits.json`
- Changing the "logic" entry in `top-10000-project-gutenberg-words.json` from `HROPBL/EUBG` to `HROPBLG/EUBG`

**Comment by paulfioravanti** [comment]
A similar issue:

In the current `dict.json` file, there are the following strokes for "emerge", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"AOE/PHERPBG": "emerge",
"AOE/PHERPBLG": "emerge",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "emerge" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L9759

`"AOE/PHERPBG": "emerge` looks like a mis-stroke to me, though this time missing the `L` stroke to make the full `PBLG` "j" sound. So, I would like to propose:

- Removing `"AOE/PHERPBG": "emerge"` from `dict.json`
- Adding `"AOE/PHERPBG": "emerge"` to `bad-habits.json`
- Changing the "logic" entry in `top-10000-project-gutenberg-words.json` from `AOE/PHERPBG` to `AOE/PHERPBLG`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti — all 6 suggestions sounds great
