### ISSUE TITLE
Strokes for "boundary", "invent", and "finely" missing full `PB` stroke for "n" sound.

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#186]
In the current `dict.json` file, there are the following strokes for "boundary", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PWOUBD/REU": "boundary",
"PWOUPB/TKAEUR": "boundary",
"PWOUPB/TKREU": "boundary",
"PWOUPBD/REU": "boundary",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "boundary" is:

https://github.com/didoesdigital/steno-dictionaries/blob/2896e5f70fdfe006afc1924aad07079e18ad1a8e/dictionaries/top-10000-project-gutenberg-words.json#L6067

`"PWOUBD/REU": "boundary"` looks like a mis-stroke to me, as it is missing the `P` stroke next to `B` to make the full `PB` "n" sound. So, I would like to propose:

- Removing `"PWOUBD/REU": "boundary"` from `dict.json`
- Adding `"PWOUBD/REU": "boundary"` to `bad-habits.json`
- Changing the "boundary" entry in `top-10000-project-gutenberg-words.json` from `PWOUBD/REU` to `PWOUPBD/REU`

**Comment by paulfioravanti** [comment]
Further to this, I have another missing-a-full-"n" sound stroke:

In the current `dict.json` file, there are the following strokes for "invent", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EUPB/SREPBT": "invent",
"EUPB/SREPT": "invent",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "invent" is:

https://github.com/didoesdigital/steno-dictionaries/blob/2896e5f70fdfe006afc1924aad07079e18ad1a8e/dictionaries/top-10000-project-gutenberg-words.json#L8375

This is the same issue as "boundary", so I'd also like to propose:

- Removing `"EUPB/SREPT": "invent"` from `dict.json`
- Adding `"EUPB/SREPT": "invent"` to `bad-habits.json`
- Changing the "invent" entry in `top-10000-project-gutenberg-words.json` from `PEUPB/SREPT` to `EUPB/SREPBT`

**Comment by paulfioravanti** [comment]
Another stroke missing a "n" sound stroke:

In the current `dict.json` file, there are the following strokes for "finely", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"TPAOEUBL/HREU": "finely",
"TPAOEUPB/HREU": "finely",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "finely" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L6540

In this case, the `"TPAOEUBL/HREU": "finely"` stroke doesn't seem right to be as it's not using `PB` for "n", and I'm not sure of the purpose of the final `L` in the first stroke. So, here, I'd also like to propose:

- Removing `"TPAOEUBL/HREU": "finely"` from `dict.json`
- Adding `"TPAOEUBL/HREU": "finely"` to `bad-habits.json`
- Changing the "finely" entry in `top-10000-project-gutenberg-words.json` from `TPAOEUBL/HREU` to `TPAOEUPB/HREU`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti — that all sounds good to me.

It's worth noting you can also write "boundary" using the word "bound" and the suffix `"AER": "{^ary}",`.  It's probably worth adding to the `condensed-strokes.json`

**Comment by paulfioravanti** [comment]
Another stroke of this ilk that I can add to the list:

In the current `dict.json` file, there are the following strokes for "dimensions", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"TKPHEPBGS/-S": "dimensions",
"TKPHEPGS/-S": "dimensions",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "dimensions" is:

https://github.com/didoesdigital/steno-dictionaries/blob/ef6a38a679db5a27769e0c9e2116f2d02a09165f/dictionaries/top-10000-project-gutenberg-words.json#L7304

Here, I'd also like to propose:

- Removing `"TKPHEPGS/-S": "dimensions"` from `dict.json`
- Adding `"TKPHEPGS/-S": "dimensions"` to `bad-habits.json`
- Changing the "dimensions" entry in `top-10000-project-gutenberg-words.json` from `TKPHEPGS/-S` to `TKPHEPBGS/-S`
