### ISSUE TITLE
Stroke for "blossoms" missing full `HR` stroke for "l" sound

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#187]
In the current `dict.json` file, there are the following strokes for "blossoms", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PWHROS/SOPL/-S": "blossoms",
"PWROS/SOPL/-S": "blossoms",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "blossoms" is:

https://github.com/didoesdigital/steno-dictionaries/blob/2896e5f70fdfe006afc1924aad07079e18ad1a8e/dictionaries/top-10000-project-gutenberg-words.json#L6009

`"PWROS/SOPL/-S": "blossoms"` looks like a mis-stroke to me, as it is missing the `H` stroke next to `R` to make the full `HR` "l" sound. So, I would like to propose:

- Removing `"PWROS/SOPL/-S": "blossoms"` from `dict.json`
- Adding `"PWROS/SOPL/-S": "blossoms"` to `bad-habits.json`
- Changing the "blossoms" entry in `top-10000-project-gutenberg-words.json` from `PWROS/SOPL/-S` to `PWHROS/SOPL/-S`

**Comment by paulfioravanti** [comment]
The stroke for "deliberately" is in the same vein:

In the current `dict.json` file, there are the following strokes for "deliberately", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"TKHREUB/RAT/HREU": "deliberately",
"TKHREUBT/RAT/HREU": "deliberately",
"TKREUB/RAT/HREU": "deliberately",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "deliberately" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L4439

`"TKREUB/RAT/HREU": "deliberately"` looks like a mis-stroke to me, as it is missing the `H` stroke next to `R` to make the full `HR` "l" sound. So, I would like to propose:

- Removing `"TKREUB/RAT/HREU": "deliberately"` from `dict.json`
- Adding `"TKREUB/RAT/HREU": "deliberately"` to `bad-habits.json`
- Changing the "deliberately" entry in `top-10000-project-gutenberg-words.json` from `TKREUB/RAT/HREU` to `TKHREUB/RAT/HREU`

**Comment by didoesdigital** [comment]
Thanks, @paulfioravanti ! All 6 points sound good.
