### ISSUE TITLE
Issue with stroke for "unfinished"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#188]
In the current `dict.json` file, there are the following strokes for "unfinished", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"UPB/TPERPD/EURBD": "unfinished",
"UPB/TPEUPB/EURB/-D": "unfinished",
"UPB/TPEUPB/EURBD": "unfinished",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "unfinished" is:

https://github.com/didoesdigital/steno-dictionaries/blob/2896e5f70fdfe006afc1924aad07079e18ad1a8e/dictionaries/top-10000-project-gutenberg-words.json#L8347

`"UPB/TPERPD/EURBD": "unfinished"` looks like a mis-stroke to me, but since the `TPERPD` stroke part is so different to what I would expect for the word, I'm wagering I'm missing some steno knowledge (perhaps it's from another theory...?). Regardless, given that the two-stroke entry for "finished" in `dict.json` is `TPEUPB/EURBD`, I would like to at least propose standardising on that by:

- Changing the "unfinished" entry in `top-10000-project-gutenberg-words.json` from `UPB/TPERPD/EURBD` to `UPB/TPEUPB/EURBD`

If `UPB/TPERPD/EURBD` can be considered a mis-stroke, then I'd also propose removing it from `dict.json` and adding it to `bad-habits.json`.

**Comment by didoesdigital** [comment]
I don't know of any reason for the `TPERPD` part of `"UPB/TPERPD/EURBD": "unfinished"`, other than a misstroked effort to hit `RB` for "sh", as well as missing the `U`, and trying to "fold" the `D` into that stroke as well…

Changing it to `UPB/TPEUPB/EURBD` sounds good, ta.

Alternatively, we could add `"UPB/TP*EURBD": "unfinished",` to `condensed-strokes.json`.

**Comment by paulfioravanti** [comment]
> Changing it to UPB/TPEUPB/EURBD sounds good, ta.

In the PR for this, I'll also mark `"UPB/TPERPD/EURBD": "unfinished"` as a mis-stroke and add it to `bad-habits.json`

> Alternatively, we could add "UPB/TP*EURBD": "unfinished", to condensed-strokes.json.

Why not both? 😉 I'll add this in as well.
