### ISSUE TITLE
Question about stroke for "unlikely"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#189]
In the current `dict.json` file, there are the following stroke for "unlikely", which is valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"UPB/HRAOEUBG/HREU": "unlikely"
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "unlikely" is:

https://github.com/didoesdigital/steno-dictionaries/blob/2896e5f70fdfe006afc1924aad07079e18ad1a8e/dictionaries/top-10000-project-gutenberg-words.json#L8476

The `"UPB/HRAOEULG": "unlikely"` stroke used here would seem to come from the `condensed-strokes.json` dictionary:

https://github.com/didoesdigital/steno-dictionaries/blob/2896e5f70fdfe006afc1924aad07079e18ad1a8e/dictionaries/condensed-strokes.json#L1259

It would seem, though, that Plover does not have this stroke as an entry for "unlikely". It only has:

```txt
unlikely:
   UPB/HRAOEUL
   UPB/HRAOEUBG/HREU
``` 

`UPB/HRAOEUL` has already been marked as a mis-stroke:

https://github.com/didoesdigital/steno-dictionaries/blob/2896e5f70fdfe006afc1924aad07079e18ad1a8e/dictionaries/bad-habits.json#L691

Which leaves `UPB/HRAOEUBG/HREU` as the only valid stroke that's also in Plover. So, my question is:

should the entry in `top-10000-project-gutenberg-words.json` be changed from `UPB/HRAOEULG` to `UPB/HRAOEUBG/HREU`? `UPB/HRAOEULG` does indeed output to "unlikely", but should Plover strokes be prioritised in this case?

**Comment by didoesdigital** [comment]
Good question! This condensed stroke is using the prefix stroke `"UPB": "{un^}",` and the entry for `"HRAOEULG": "likely",` in Plover. `HRAOEULG` is consistent with:

```
"HRAOEULG": "likely",
"HRAOEULG/HAOD": "likelihood",
"HRAOEULGD": "likelihood",
"THRAOEULG": "likely to",
 ```

It seems kind of like a brief format leaning on `*LG` for "lk" sounds.

Git log shows that it replaced entries using short "i" sound and the misstroke you called out in c866cd31f4b3c4d02ba21a1fddd26eb6307ac0f4:

```
$ git log -S'"UPB/HRAOEULG": "unlikely",' -- dictionaries/top-10000-project-gutenberg-words.json --follow-parent
```

As far as prioritising Plover strokes, it's consistent enough with the dictionary so I think it can stay as it is. Do you think?

**Comment by paulfioravanti** [comment]
Thanks for the explanation, @didoesdigital! Leaving this stroke alone as-is good to me.
