### ISSUE TITLE
Stroke for "angrily" using `L` rather than `G` for its "ang" sound

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#190]
In the current `dict.json` file, there are the following strokes for "angrily", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"AEUPBG/REU/HREU": "angrily",
"APBG/REU/HREU": "angrily",
"APBG/TKPWREU/HREU": "angrily",
"APBL/REU/HREU": "angrily",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "angrily" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L4994

`"APBL/REU/HREU": "angrily"` looks like a mis-stroke to me using `L` rather than `G`, especially since Plover theory specifically marks `PBG` as being an "ng" sound. So, I would like to propose:

- Removing `"APBL/REU/HREU": "angrily"` from `dict.json`
- Adding `"APBL/REU/HREU": "angrily"` to `bad-habits.json`
- Changing the "angrily" entry in `top-10000-project-gutenberg-words.json` from `APBL/REU/HREU` to `APBG/REU/HREU`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti — sounds like a great change.
