### ISSUE TITLE
Current stroke for "representations" outputs "reputations"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#191]
In the current `dict.json` file, there is the following stroke for "representations":

```json
"REP/TAEUGS/-S": "representations"
```

Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) does not have a named stroke for "representations".

The `top-10000-project-gutenberg-words.json` dictionary also uses this stroke:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L5128

However, this looks like a mistake, since `REP/TAEUGS` is the stroke for "reputation" in Plover, and `REP/TAEUGS/-S` results in "reputations", so I would like to propose:

- Removing `"REP/TAEUGS/-S": "representations"` from `dict.json`
- Potentially adding `"REP/TAEUGS/-S": "representations"` to `bad-habits.json`(?) Since this looks like a mistake, perhaps this step does not need to happen...?
- If a named stroke for "representations" should exist in `dict.json`, even though it doesn't in Plover, then add an `"REPT/TAEUGS/-S": "representations"` entry to it
- Changing the "reputations" entry in `top-10000-project-gutenberg-words.json` from `REP/TAEUGS/-S` to `REPT/TAEUGS/-S`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti , these changes look good, including adding `"REP/TAEUGS/-S": "representations"` to `bad-habits.json`.  Although instead of adding `"REPT/TAEUGS/-S": "representations"` to `dict.json`, let's add it to `condensed-strokes.json`.
