### ISSUE TITLE
Extra KWREU "y" stroke causing mis-strokes

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#192]
In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "mysteries" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L5212

However, the `PHOEUFRT/KWREU/-S` stroke results in "mysteryies". If the `KWREU` stroke is removed to make `PHOEUFRT/-S`, then we get the expected output of "mysteries". Therefore, I would like to propose:

- Changing the "mysteries" entry in `top-10000-project-gutenberg-words.json` from `PHOEUFRT/KWREU/-S` to `PHOEUFRT/-S`

Plover does not have a named entry for "mysteries", so I'm assuming that this entry wouldn't need to be added to `dict.json`, but if that is not the case, then I'm happy to add it there as well.

**Comment by paulfioravanti** [comment]
The stroke for "fancies" is also in the same vein.

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "fancies" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L5527

However, the `TPAPB/SEU/KWREU/-S` stroke results in "fancyies". If the `KWREU` stroke is removed to make `TPAPB/SEU/-S`, then we get the expected output of "fancies". Therefore, I would like to propose:

- Changing the "fancies" entry in `top-10000-project-gutenberg-words.json` from `TPAPB/SEU/KWREU/-S` to `TPAPB/SEU/-S`

Like "mysteries", Plover does not have a named entry for "fancies", so I'm assuming that this entry wouldn't need to be added to `dict.json`, but if that is not the case, then I'm also happy to add it there as well.

**Comment by paulfioravanti** [comment]
Similar issue for "faculties":

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "faculties" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L4835

However, the `TPABG/UT/KWREU/-S` stroke results in "facultyies". If the `KWREU` stroke is removed to make `TPABG/UT/-S`, then we get the expected output of "faculties". Here, though, I'd go a bit further and propose that `TPABG/ULT/-S` with an `L` stroke is a more accurate entry. Therefore, I would like to propose:

- Changing the "faculties" entry in `top-10000-project-gutenberg-words.json` from `TPABG/UT/KWREU/-S` to `TPABG/ULT/-S`

Also no named entry in Plover here, so it can be added to `dict.json` if needed.

**Comment by paulfioravanti** [comment]
Similar issue for "duties":

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "duties" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L1531

In the case of "duties", the issue doesn't result in a mis-stroke: the 3-stroke entry outputs "duties" as expected. But, `TKAOUT/-S`, without the `KWREU` stroke, also results in "duties" being output. I would think that perhaps saving a stroke would be beneficial, so I'd like to propose:

- Changing the "duties" entry in `top-10000-project-gutenberg-words.json` from `TKAOUT/KWREU/-S` to `TKAOUT/-S`

**Comment by didoesdigital** [comment]
Great fixes, @paulfioravanti . I noticed some similar issues recently in Typey Type lessons and added a batch of new condensed stroke entries in 2e928c6. The lesson generator has some naive orthography rules and seems to have got a bunch wrong. I expect there a few more stray examples kicking around in `top-10000-project-gutenberg-words.json` that use `/KWREU/-S` where they shouldn't.

In general, for the entries that don't exist in Plover at all, we can add them to `condensed-strokes.json` and update them in `top-10000-project-gutenberg-words.json`.

Your suggestions all look good, including "faculties" and "duties"

**Comment by paulfioravanti** [comment]
Thanks, @didoesdigital. You're right about there being a few more stray examples :) Along with "mysteries", "fancies", "faculties", and "duties", I've uncovered a couple of others this morning, which I'll add to the batch:

"missionaries":

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L6802

This should outputs "missionaryies", so needs to be changed to `PHEUGS/REU/-S`.

"sympathies":

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L6836

This should outputs "sympathyies", so needs to be changed to `SEUPL/THEU/-S`.

**Comment by didoesdigital** [comment]
Great work! Let's fix 'em

**Comment by paulfioravanti** [comment]
Another one for this list:

"notifies":

https://github.com/didoesdigital/steno-dictionaries/blob/b33b48f564b80ae37abd5fe6de4a4ce53c26fd37/dictionaries/top-10000-project-gutenberg-words.json#L7843

This outputs to "notifyies", so needs to be changed to `TPHOEUF/-S`.

**Comment by paulfioravanti** [comment]
Another one for this list:

"lilies":

https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/top-10000-project-gutenberg-words.json#L8457

This outputs to "lillyies", so needs to be changed to `HREUL/KWREU/-S`.

**Comment by paulfioravanti** [comment]
Another one:

"fairies":

https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/top-10000-project-gutenberg-words.json#L8980

This outputs to "fairyies", so needs to be changed to `TPAEUR/REU/-S`.
