### ISSUE TITLE
Current stroke for "worshipped" results in single "p"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#193]
In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "worshipped" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L6206

However, the `WOR/SH-P/-D` stroke results in "worshiped" with a single "p". Changing the stroke to `WOR/SH-P/PD` results in the expected "worshipped" output. Therefore, I would like to propose:

- Changing the "worshipped" entry in `top-10000-project-gutenberg-words.json` from `WOR/SH-P/-D` to `WOR/SH-P/PD`

Plover does not have a named entry for "worshipped", so I'm assuming that this entry wouldn't need to be added to `dict.json`, but if that is not the case, then I'm happy to add it there as well.

**Comment by didoesdigital** [comment]
Thanks for catching this. I think we want a left side `P` instead of a right side `-P`so it would need to be `WOR/SH-P/P-D` with a dash in the last stroke to match the suffix `"P-D": "{^ped}",`. Let's add this entry to `condensed-strokes.json`
