### ISSUE TITLE
Stroke for "antiquity" missing `E` stroke for its "i" sound

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#194]
In the current `dict.json` file, there are the following strokes for "antiquity", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"APB/TEUBG/TEU": "antiquity",
"APB/TEUBG/WEU/TEU": "antiquity",
"APB/TEUBG/WEUT": "antiquity",
"APB/TUBG/TEU": "antiquity",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "antiquity" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L5131

`"APB/TUBG/TEU": "antiquity"` looks like a mis-stroke to me, missing the `E` in the second stroke for its "i" sound. So, I would like to propose:

- Removing `"APB/TUBG/TEU": "antiquity"` from `dict.json`
- Adding `"APB/TUBG/TEU": "antiquity"` to `bad-habits.json`
- Changing the "antiquity" entry in `top-10000-project-gutenberg-words.json` from `APB/TUBG/TEU` to `APB/TEUBG/TEU`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti ! Ship it!
