### ISSUE TITLE
Is Plover stroke for "ceremonies" a mis-stroke (missing full `PB` stroke for "n")?

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#195]
In the current `dict.json` file, there is following stroke for "ceremonies", which is valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"SER/PHOEP/-S": "ceremonies"
```

It's also used in `top-10000-project-gutenberg-words.json` dictionary:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L5218

Given that the stroke for the singular "ceremony" is

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L2926

I'm surprised that Plover does not also list a `SER/PHOEPB/-S` stroke for "ceremonies": it only lists `SER/PHOEP/-S`. So, my questions are:

- Does this look like a mistake/mis-stroke, or is it following some steno rule to truncate the `B`, perhaps...?
- Given that `SER/PHOEPB/-S` outputs "ceremonies" as expected when stroked, would this be a candidate for inclusion in the dictionaries, even though it's not specifically in Plover?

**Comment by didoesdigital** [comment]
That is surprising! This is a good fix, and I can see no reason for the `B` to be missing beyond being a misstroke. Let's add `SER/PHOEPB/-S` to `condensed-strokes.json` and update it in `top-10000-project-gutenberg-words.json`
