### ISSUE TITLE
Issue with accent stroke for "refuge"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#196]
In the current `dict.json` file, there are the following strokes for "refuge", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"RAF/AOUPBLG": "refuge",
"RAOEF/AOUPBLG": "refuge",
"RE/TPAOUPBLG": "refuge",
"REF/AOUPBLG": "refuge",
"REF/KWRAOUPBLG": "refuge",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "refuge" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L3053

The pronunciation of the word "refuge" may differ across accents, so this may be very subjective, but rather than `"RAF/AOUPBLG": "refuge"`, `"REF/AOUPBLG": "refuge"` sounds more like the correct stroke to me. I'm not sure whether I'd propose marking any of the other entries as mis-strokes due to accents, but I'd like to at least propose:

- Changing the "refuge" entry in `top-10000-project-gutenberg-words.json` from `RAF/AOUPBLG` to `REF/AOUPBLG`

**Comment by didoesdigital** [comment]
As a fellow Australian, I'm not in a position to provide an alternative view of how accent plays into this! That said, there are almost no other examples of dictionary entries starting with `RA` to achieve a "ˈre-" sound. Let's move the previous entry to `bad-habits.json` as well as updating the entry in `top-10000-project-gutenberg-words.json`
