### ISSUE TITLE
Stroke for "events" missing the `F` stroke for "v"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#197]
In the current `dict.json` file, there are the following strokes for "event" and "events", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"*EFPBT": "event",
"AOE/SREPBT": "event",
"AOEFPBT": "event",
"AOEPBT": "event",
"EFPBT": "event",
```

```json
"AOEFPBTS": "events",
"AOEPBTS": "events",
"AOEPBTS/-S": "events",
"AOEPBTSZ": "events",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the strokes used for "event" and "events" are:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L1847

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L1238

There seems to be some leeway between the pronunciation of the word ("event" vs "ēvent"), but I feel that stroke entries that contain the `F` stroke for the "v" sound should be prioritised over those that don't (I'm not sure at this point whether entries without an `F` should be marked as mis-strokes). So, I'd like to propose at least to:

- Change the "events" entry in `top-10000-project-gutenberg-words.json` from `AOEPBTS` to `AOEFPBTS`

**Comment by didoesdigital** [comment]
Good one, @paulfioravanti . I feel like I learned this misstroke (`AOEPBT`) as if it were canon and now I can find no reason for it. Yes, let's add the `F` in 'AOEFPBTS`.

**Comment by didoesdigital** [comment]
Maybe it was the consistency with `RAOEPBT` for "recent"?
