### ISSUE TITLE
Stroke for "extensive" is a brief that has mistaken output when used with vanilla Plover

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#198]
In the current `dict.json` file, there are the following strokes for "extensive", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EBGS/TEPBS/EUF": "extensive",
"EBGS/TEPBS/EUFL": "extensively",
"EPBGS/TEPBS/EUF": "extensive",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "extensive", though, is quite different:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L3397

This would seem to come from `briefs.json`:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/briefs.json#L106

Since `STEPBS/EUF` in vanilla Plover outputs "sentencive", I think it's probably best that it does not appear in Typey-Type. So, I'd like to propose:

- Changing the "extensive" entry in `top-10000-project-gutenberg-words.json` from `STEPBS/EUF` to `EBGS/TEPBS/EUF`

**Comment by didoesdigital** [comment]
Thanks, sounds good to me @paulfioravanti
