### ISSUE TITLE
Stroke for "hopeless" that begins with a `P` looks like a mis-stroke

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#199]
In the current `dict.json` file, there are the following strokes for "hopeless", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"HOEP/-FL/*F/-LS": "hopeless",
"HOEP/-LS": "hopeless",
"HOEP/HRES": "hopeless",
"POEP/-LS": "hopeless",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "hopeless" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L3761

Stroking "hopeless" with a starting `P` looks a lot like a mis-stroke to me, especially since Plover has only one named stroke entry for "hope", which is `HOEP`, so I'd like to propose:

- Removing `"POEP/-LS": "hopeless"` from `dict.json`
- Adding `"POEP/-LS": "hopeless"` to `bad-habits.json`
- Changing the "hopeless" entry in `top-10000-project-gutenberg-words.json` from `POEP/-LS` to `HOEP/-LS`

**Comment by paulfioravanti** [comment]
There is another stroke I found that begins with an unexpected `P` that I'll add to this thread:

In the current `dict.json` file, there are the following strokes for "tropical", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PROP/K-L": "tropical",
"TROP/K-L": "tropical",
"TROP/KAL": "tropical",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "tropical" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L6785

Stroking "tropical" with a starting `P` looks a lot like a mis-stroke to me, so I'd like to propose:

- Removing `"PROP/K-L": "tropical"` from `dict.json`
- Adding `"PROP/K-L": "tropical"` to `bad-habits.json`
- Changing the "tropical" entry in `top-10000-project-gutenberg-words.json` from `PROP/K-L` to `TROP/K-L`

**Comment by didoesdigital** [comment]
Yep, let's fix both of these! Thanks @paulfioravanti !
