### ISSUE TITLE
Use of Plover vs StenEd conventions for words ending in -mp

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#20]
In Plover Theory, the [main way to write words ending in "-mp" is to end the stroke with `*PL`](https://www.artofchording.com/compounds/mp.html#frp-for-mp). Eg:

- `HU*PL`: hump
- `PU*PL`: pump

Currently, all the dictionaries in this repo would seem to use the StenEd convention of `-FRP`. Eg:

- `HUFRP`: hump
- `PUFRP`: pump

Is there a reasoning behind this, whether it be personal preference or otherwise? If there is no particular preference, would creating a PR that changes the strokes for words ending in "-mp" to use Plover Theory be of value?

While learning Plover, I internalised the `*PL` stroke for "-mp" and was surprised to see it in Typey-Type, but since both methods are valid I'd thought I'd open this issue to clarify.

**Comment by didoesdigital** [comment]
Great question, @paulfioravanti. The only reason Typey Type would be using `*PL` for "-mp" is that it automatically prefers strokes without asterisks over strokes with the same number of keys and asterisks. In many cases, the stroke without the asterisk is easier to write and often as accurate.

As far as I can tell, while `*PL` is canonical Plover theory and what Mirabai uses, it is prone to conflicts while `-FRP` is generally more reliable. For example, `"A*PL": "a.m.",` makes it impossible to write "amp" using `*PL` for "-mp". Similarly, `"APL": "am",` makes it impossible to write "apple" using `APL` and adding as asterisk to disambiguate would also conflict `a.m.`. I cannot find any counter argument for preferring `*PL` over `-FRP`.

`-FRP` as "-mp" also aligns with [`-FR` as "-m"](https://github.com/openstenoproject/plover/wiki/Brief-Ideas).

If we wanted to ensure Typey Type prefers `*PL` to match Plover theory, we could remove all the `-FRP` entries, which doesn't feel quite right.

If we wanted to be more consistent about using `-FRP`, we might add additional entries for all the `-mp` words that only using `*PL`. We could add them to a preferences dictionary, as I've started to do for some [preferences on this branch](https://github.com/didoesdigital/steno-dictionaries/pull/2/files#diff-04c6e90faac2675aa89e2176d2eec7d8R750). I'd need to highlight this somewhere on Typey Type.

Given Typey Type already attempts to improve upon Plover's default dictionary by removing misstrokes, it might be nice to promote the use of `-FRP`. What do you think?

**Comment by paulfioravanti** [comment]
Thanks for the thoughtful response, and for introducing me to `-FR` as "-m" (I hadn't seen the hidden patterns page on the Plover wiki outlining it, nor seen it outlined in other Plover learner texts). Given what you've written, I can agree that no change to the "-mp" word entries are necessary.
