### ISSUE TITLE
Stroke for "assassination" missing an `S` stroke

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#200]
In the current `dict.json` file, there are the following strokes for "assassination", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"A/A/SAS/TPHAEUGS": "assassination",
"A/AS/STPHAEUGS": "assassination",
"A/AS/TPHAEUGS": "assassination",
"A/SAS/TPHAEUGS": "assassination",
"A/SES/TPHAEUGS": "assassination",
"AS/ASZ/TPHAEUGS": "assassination",
"AS/SAS/TPHAEUGS": "assassination",
"AS/SASZ/TPHAEUGS": "assassination",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "assassination" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L9851

`"A/AS/TPHAEUGS": "assassination"` potentially looks like a mis-stroke to me, as it is missing a leading `S` in the second stroke to make the "sas" sound. Some of the other strokes also look a bit suss to me, but regardless, I would like to at least propose:

- Removing `"A/AS/STPHAEUGS": "assassination"` and  `"A/AS/TPHAEUGS": "assassination"` from `dict.json`
- Adding `"A/AS/STPHAEUGS": "assassination"` and `"A/AS/TPHAEUGS": "assassination"` to `bad-habits.json`
- Changing the "assassination" entry in `top-10000-project-gutenberg-words.json` from `A/AS/STPHAEUGS` to `A/SAS/TPHAEUGS`

**Comment by didoesdigital** [comment]
Great idea @paulfioravanti . Which other strokes look suss to you? `"A/SES/TPHAEUGS": "assassination",` and `"A/A/SAS/TPHAEUGS": "assassination",` could probably go.

**Comment by paulfioravanti** [comment]
@didoesdigital Yup, it was those two others 😄 We'll put them on the chopping block as well.
