### ISSUE TITLE
Plover single-stroke entry for "practical" overrides some dictionary multi-stroke entries

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#201]
In the current `dict.json` file, there are the following strokes for "practical", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PRA*BGT/K-L": "practical",
"PRABG/TEU/KAL": "practical",
"PRABG/TEUBG/A*L": "practical",
"PRABG/TEUBG/KAL": "practical",
"PRABGT/K-L": "practical",
"PRABGT/KAL": "practical",
"PRABGT/KRAL": "practical",
"PRABGTD/K-L": "practical",
```

This issue is less about potential mis-strokes in the dictionaries and more about the effects the addition of `PRABGT` to Plover as a single-stroke entry for "practical" has in Typey Type.

Given that the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "practical" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L1708

When you stroke the first part of this stroke, since it outputs "practical", Typey Type thinks it is done, and moves on to the next word, leaving the user (or me at least) a bit surprised.

I'm not sure if the addition of `"PRABGT": "practical"` to Plover technically makes the following affected strokes now mis-strokes:

```json
"PRABGT/K-L": "practical",
"PRABGT/KAL": "practical",
"PRABGT/KRAL": "practical",
```

But regardless, I'd like to propose the following to help reduce surprises in Typey Type:

- Add `"PRABGT": "practical"` entry to `dict.json`
- Change the "practical" entry in `top-10000-project-gutenberg-words.json` from `PRABGT/K-L` to `PRABGT`

**Comment by didoesdigital** [comment]
Yep, let's do it. There are a few other examples throughout the dictionary where the first stroke writes the word and the second stroke is an optional suffix to also write the same word. So far, it hasn't caused me any issues. For now, let's leave these as they are:

```
"PRABGT/K-L": "practical",
"PRABGT/KAL": "practical",
"PRABGT/KRAL": "practical",
 ```
