### ISSUE TITLE
Stroke for "Francis" missing an `S`

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#202]
In the current `dict.json` file, there are the following strokes for "Francis", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"TPRAPB/EUS": "Francis",
"TPRAPB/SEUS": "Francis",
"TPRAPBS/EUS": "Francis",
"TPRAPBSZ/EUS": "Francis",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "Francis" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L2696

`"TPRAPB/EUS": "Francis"` without an `S` stroke for the "cis" part of the name potentially looks like a mis-stroke to me, so I would like to propose:

- Removing `"TPRAPB/EUS": "Francis"` from `dict.json`
- Adding `"TPRAPB/EUS": "Francis"` to `bad-habits.json`
- Changing the "Francis" entry in `top-10000-project-gutenberg-words.json` from `TPRAPB/EUS` to `TPRAPB/SEUS`

**Comment by didoesdigital** [comment]
Looks good to me, @paulfioravanti !
