### ISSUE TITLE
Issue with number strokes

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#203]
**Issue 1:**

In the current `numbers.json` file, there are the following strokes for "900", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/numbers.json#L34
https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/numbers.json#L260

The issue I have here is that I find `-9Z` impossible to stroke without doing a hand shift (Philly shift?), and so think it would be better to see `EU9`, rather than `-9Z` show up in Typey Type as the stroke for "900". Would you agree? If so, can this change be done via a change to the dictionaries?

**Issue 2:**

There are no named strokes in Plover for thousand-numbers: "1000", "2000" etc. In Typey Type, it would seem that the strokes for them are appearing to come from the `numbers-powerups.json`. For numbers of "1000" up to "5000", it has the `x0Z`-style strokes:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/numbers-powerups.json#L2-L6

While for numbers "6000" and up, there are two flavours of strokes: `x0Z`-style and `x/THUZ`-style strokes:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/numbers-powerups.json#L7-L14

The issue here is that in Typey Type, the `x0Z`-style strokes are used for "1000"-"5000", while `x/THUZ`-style strokes are used for "6000"-"10000", and vanilla Plover does not recognise the `x0Z`-style strokes, but it does recognise `x/THUZ` strokes, it would seem, through this entry:

```
{&000}:
   THUZ
```

So, I'd like to propose:

- Add the following entries to `numbers-powerups.json`, so all thousands number can be stroked with vanilla Plover (and hopefully enforce their appearance in Typey Type):
  - `"1/THUZ": "1000",`
  - `"2/THUZ": "2000",`
  - `"3/THUZ": "3000",`
  - `"4/THUZ": "4000",`
  - `"5/THUZ": "5000",`

**Comment by didoesdigital** [comment]
Thanks for flagging the issues here. This lesson has been so frustrating throughout Typey Type's existence and differing versions of Plover.

Sure, let's add those. If it doesn't enforce it in Typey Type I may need manually deal with that in the static lesson generator.

**Comment by paulfioravanti** [comment]
Since those number entries are technically all "condensed strokes" since they're not in Plover, would it be helpful adding, say, the `x0Z`-style strokes directly to the `condensed-strokes.json` dictionary?
