### ISSUE TITLE
Stroke for "inaccessible" using non-Plover brief in Typey Type

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#204]
In the current `dict.json` file, there is the following stroke for "inaccessible", which is valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EUPB/ABG/SES/EUBL": "inaccessible"
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "inaccessible" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L9429

This would seem to come from the `briefs.json` dictionary:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/briefs.json#L100

Would it be better to have the Plover stroke show up in Typey Type? If so, then I would like to propose:

- Changing the "inaccessible" entry in `top-10000-project-gutenberg-words.json` from `EUPB/SESZ/-BL` to `EUPB/ABG/SES/EUBL`

**Comment by didoesdigital** [comment]
Thanks for this @paulfioravanti . If ["access" ever gets fixed in Plover](https://github.com/didoesdigital/steno-dictionaries/blob/master/README.md#access-and-excess), we can restore this brief. Until then, let's do as you suggest.
