### ISSUE TITLE
Stroke for "acquaint" missing final `T` stroke

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#205]
In the current `dict.json` file, there are the following strokes for "acquaint", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"A/KWAEUPB": "acquaint",
"A/KWAEUPBT": "acquaint",
"ABG/KWAEUPBT": "acquaint",
"ABG/WAEUPBT": "acquaint",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "acquaint" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L9331

`"A/KWAEUPB": "acquaint"` without an `T` stroke at the end of the word potentially looks like a mis-stroke to me, so I would like to propose:

- Removing `"A/KWAEUPB": "acquaint"` from `dict.json`
- Adding `"A/KWAEUPB": "acquaint"` to `bad-habits.json`
- Changing the "Francis" entry in `top-10000-project-gutenberg-words.json` from `A/KWAEUPB` to `A/KWAEUPBT`

**Comment by didoesdigital** [comment]
Sounds good @paulfioravanti !
