### ISSUE TITLE
Question about stroke for "detestable"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#206]
In the current `dict.json` file, there are the following strokes for "detestable", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"TKE/SEFT/-BL": "detestable",
"TKE/T*ES/-BL": "detestable",
"TKE/TES/TABL": "detestable",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "detestable" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L9687

This is one I'm really not sure on, and I'm very happy to be wrong and/or for this issue to just be closed, but:

- `"TKE/SEFT/-BL": "detestable",` seems like a mis-stroke due to having the `S` rather than a `T` at the start of the second stroke
- I probably wouldn't put forward `TKE/T*ES/-BL` as a replacement due to it using the asterisk and not being a great fit since it loses a `T` stroke after `S`
- `TKE/TES/TABL` seems like the "most right" pronunciation-wise out of Plover's set
- But, the stroke `TKE/TEFT/-BL`, which is not in Plover, outputs "detestable" and it seems, at least to me, to be the most appropriate stroke for the word. But, obviously it's not "official" in any way, so I have to assume there's an issue with it that I haven't thought of

I have to assume that introducing `TKE/TEFT/-BL` to the dictionaries can't be considered a valid option, so would it then be appropriate to propose:

- Changing the "detestable" entry in `top-10000-project-gutenberg-words.json` from `TKE/SEFT/-BL` to `TKE/TES/TABL`

Or, is it better to keep the stroke as-is for learners to have another example of usage of the `-BL` suffix?

**Comment by didoesdigital** [comment]
Nice one, @paulfioravanti . `TKE/TEFT/-BL` uses prefix and suffix strokes for `TKE` (de-) and `-BL`(-able) and the word "test" via `TEFT`, so I think this is a good candidate for adding to the `condensed-strokes.json` dictionary and updating in the `top-10000-project-gutenberg-words.json` dictionary.
