### ISSUE TITLE
Subjective preference for stroke for "unscrupulous"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#207]
In the current `dict.json` file, there are the following strokes for "unscrupulous", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"UPB/KRAOUP/HROUS": "unscrupulous",
"UPB/SKRAOUP/HRUS": "unscrupulous",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "unscrupulous" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L9770

I don't think I'd say that `"UPB/KRAOUP/HROUS": "unscrupulous"` looks like a mis-stroke, but perhaps I'd subjectively say that perhaps `"UPB/SKRAOUP/HRUS": "unscrupulous"` is a slightly better match for the word, pronunciation-wise, and it should appear in Typey Type over the other stroke. So, I'd like to propose:

- Changing the "unscrupulous" entry in `top-10000-project-gutenberg-words.json` from `UPB/KRAOUP/HROUS` to `UPB/SKRAOUP/HRUS`

**Comment by didoesdigital** [comment]
Sounds good @paulfioravanti ! `"UPB/KRAOUP/HROUS": "unscrupulous"` missing the `S` key does seem like a misstroke to me so I'd be happy to also move that to the `bad-habits.json` dictionary.
