### ISSUE TITLE
Stroke for "apprentice" missing an `R`

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#208]
In the current `dict.json` file, there are the following strokes for "apprentice", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"A/PEPBT/EUS": "apprentice",
"A/PREPB/TEUS": "apprentice",
"A/PREPBT/EUS": "apprentice",
"AP/PREPB/TEUS": "apprentice",
"AP/PREPBT/EUS": "apprentice",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "apprentice" is:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L9804

`"A/PEPBT/EUS": "apprentice"` without an `R` stroke looks like a mis-stroke to me, so I would like to propose:

- Removing `"A/PEPBT/EUS": "apprentice"` from `dict.json`
- Adding `"A/PEPBT/EUS": "apprentice"` to `bad-habits.json`
- Changing the "apprentice" entry in `top-10000-project-gutenberg-words.json` from `A/PEPBT/EUS` to `A/PREPBT/EUS`

Also, Plover would seem to have added `PREPBT/EUS` as a stroke for "appentice", which is not currently in the dictionaries, so I would also propose:

- Adding `"PREPBT/EUS": "apprentice"` to `dict.json` (should this also go in `top-10000-project-gutenberg-words.json`?)

**Comment by didoesdigital** [comment]
All of those suggestions sound great. Let's update `top-10000-project-gutenberg-words.json` to the new entry `"PREPBT/EUS": "apprentice"`
