### ISSUE TITLE
Does entry for "hastings" need to be a capital letter?

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#209]
In the `condensed-strokes.json` dictionary, there is the following stroke for "hastings":

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/condensed-strokes.json#L723

It is also used in the `top-10000-project-gutenberg-words.json` dictionary:

https://github.com/didoesdigital/steno-dictionaries/blob/5a5d457574ed8cf8088e5b2c904a131fc8e8ddfa/dictionaries/top-10000-project-gutenberg-words.json#L6812

Currently, though, this stroke outputs "Hastings", with a capital letter.

In the current `dict.json` file, there is the following stroke for "Hasting", which is valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"HAEUFT/EUPBG": "Hasting"
```

I'm assuming that "Hasting" here is meant to represent the Hasting surname(?), and that `HAEUFT/EUPBG/-S` represents the surname and place name Hastings(?).

If that is the intention, then the capitalisation of the `"HAEUFT/EUPBG/-S": "hastings"` should be changed, with the entry becoming `"HAEUFT/EUPBG/-S": "Hastings"`. If not, should the entry for "hastings" be perhaps changed to fingerspelling?

If the former, I would propose:

- Changing the `"HAEUFT/EUPBG/-S": "hastings"` entry in `top-10000-project-gutenberg-words.json` and `condensed-strokes.json` to `"HAEUFT/EUPBG/-S": "Hastings"`

If the latter, I would propose:

- Changing the `"HAEUFT/EUPBG/-S": "hastings"` entry in `top-10000-project-gutenberg-words.json` and `condensed-strokes.json` to `"H*/A*/S*/T*/*EU/TPH*/TKPW*/S*": "hastings"`

**Comment by didoesdigital** [comment]
Hmm good one, @paulfioravanti . I recommend running with the former, let's update the capitalisation.
