### ISSUE TITLE
Stroke for "sinister" missing `U` stroke for its "i" sound

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#210]
In the current `dict.json` file, there are the following strokes for "sinister", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"S*EUPBS/ER": "sinister",
"SEPB/STER": "sinister",
"SEU/TPH*EUS/ER": "sinister",
"SEU/TPHEUS/TER": "sinister",
"SEUPB/EUS/TER": "sinister",
"SEUPB/STER": "sinister",
"SEUPBS/TER": "sinister",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "sinister" is:

https://github.com/didoesdigital/steno-dictionaries/blob/ef6a38a679db5a27769e0c9e2116f2d02a09165f/dictionaries/top-10000-project-gutenberg-words.json#L6857

`"SEPB/STER": "sinister"` without an `U` stroke to make the "sin" part of "sinister" looks like a mis-stroke to me (especially since all the other strokes have it), so I would like to propose:

- Removing `"SEPB/STER": "sinister"` from `dict.json`
- Adding `"SEPB/STER": "sinister"` to `bad-habits.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"SEPB/STER": "sinister"`
  - after: `"SEUPB/STER": "sinister"`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti , these changes look great
