### ISSUE TITLE
Stroke for "correctly" missing `G` stroke for "k" sound

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#212]
In the current `dict.json` file, there are the following strokes for "correctly", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"KREBGS/HREU": "correctly",
"KREBGT/HREU": "correctly",
"KREBT/HREU": "correctly",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "correctly" is:

https://github.com/didoesdigital/steno-dictionaries/blob/ef6a38a679db5a27769e0c9e2116f2d02a09165f/dictionaries/top-10000-project-gutenberg-words.json#L7074

1. `"KREBT/HREU": "correctly"` without an `G` stroke to form the "k" sound of "corre*ct*ly" looks like a mis-stroke to me
2. `"KREBGS/HREU": "correctly"` with an `S` stroke also looks like a mis-stroke to me
3. Plover has two entries for "correctly" that are not currently in any of the dictionaries:
  - `"KR*EL": "correctly"`
  - `"KRELG": "correctly"`

So I would like to propose:

- Adding `"KR*EL": "correctly"` and `"KRELG": "correctly"` to `dict.json`
- Removing `"KREBT/HREU": "correctly"` and `"KREBGS/HREU": "correctly"` from `dict.json`
- Adding `"KREBT/HREU": "correctly"` and `"KREBGS/HREU": "correctly"` to `bad-habits.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"KREBT/HREU": "correctly"`
  - after: `"KREBGT/HREU": "correctly"`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti . These changes look good. I'd be happy changing the `top-10000-project-gutenberg-words.json` entry to either `"KREBGT/HREU": "correctly"` as you have it there, encouraging good suffix use or to `"KRELG": "correctly"` per the new entry you've noted to quickly teach the brief. What's your thinking about the choice there?

**Comment by paulfioravanti** [comment]
I think that "correctly" is a common enough word that it's worth teaching one of the "official" briefs, so I'll put `"KRELG": "correctly"` into `top-10000-project-gutenberg-words.json`.
