### ISSUE TITLE
Stroke for "Arabian" missing `A` stroke for "ā" sound

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#213]
In the current `dict.json` file, there are the following strokes for "Arabian", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"A/RAEUB/KWRAPB": "Arabian",
"A/REUB/KWRAPB": "Arabian",
"AR/RAEUB/KWRAPB": "Arabian",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "Arabian" is:

https://github.com/didoesdigital/steno-dictionaries/blob/ef6a38a679db5a27769e0c9e2116f2d02a09165f/dictionaries/top-10000-project-gutenberg-words.json#L7283

`"A/REUB/KWRAPB": "Arabian"` without an `A` stroke to form the "ā" sound of "Ar*a*bian" looks like a mis-stroke to me, so I would like to propose:

- Removing `"A/REUB/KWRAPB": "Arabian"` from `dict.json`
- Adding `"A/REUB/KWRAPB": "Arabian"` to `bad-habits.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"A/REUB/KWRAPB": "Arabian"`
  - after: `"A/RAEUB/KWRAPB": "Arabian"`

**Comment by didoesdigital** [comment]
Thanks, @paulfioravanti . These changes all look good to me.

We might alternatively add a `condensed-strokes.json` entry for `"A*EURB/KWRAPB": "Arabian"`. What do you think?

**Comment by paulfioravanti** [comment]
> We might alternatively add a condensed-strokes.json entry for "A*EURB/KWRAPB": "Arabian". What do you think?

Sounds good! I'll add it in to the PR.
