### ISSUE TITLE
Strokes for "injurious" need some re-shuffling

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#215]
In the current `dict.json` file, there are the following strokes for "injurious":

```json
"SKWR*R/WOUS": "injurious",
"SKWREUR/OUS": "injurious",
"SKWR*R/KWROUS": "injurious",
"SKWR-R/KWROUS": "injurious",
"EUPB/SKWRUR/OUS": "injurious",
"EUPB/SKWRAOUR/OUS": "injurious",
"EUPB/SKWRUR/KWROUS": "injurious",
"EUPB/SKWRAOUR/KWRUS": "injurious",
"EUPB/SKWRAOUR/KWROUS": "injurious",
"SKWREUR/KWROUS": "injurious",
```
The first 8 stroke in the list above are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), but the final two strokes:

```json
"EUPB/SKWRAOUR/KWROUS": "injurious",
"SKWREUR/KWROUS": "injurious",
```

do not have a named entry in Plover. When stroked, they both produce "injurious" as expected (perhaps these two are now candidates for `condensed-strokes.json`?).

Further, Plover has two entries for "injurious" that are not currently in the dictionaries:

```json
"SKWR-R/KWRUS": "injurious",
"SKWREUR/KWROUS": "injurious",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "injurious" is:

https://github.com/didoesdigital/steno-dictionaries/blob/ef6a38a679db5a27769e0c9e2116f2d02a09165f/dictionaries/top-10000-project-gutenberg-words.json#L7387

Having an `EU` "i" sound in `"SKWREUR/OUS": "injurious"` rather than a `AOU` "ū" sound for the "jur" part of "injurious" looks like a mis-stroke to me.

The stroke that seemed most natural to me is `SKWRAOUR/OUS`, but although this gives the correct output, there is no named Plover entry for it (another `condensed-strokes.json` entry?).

Given this, and the other points above, I would like to propose:

- Adding the following strokes to `dict.json`:
  - `"SKWR-R/KWRUS": "injurious"`
  - `"SKWREUR/KWROUS": "injurious"`
- Removing the following strokes from `dict.json`:
  - `"EUPB/SKWRAOUR/KWROUS": "injurious"`
  - `"SKWREUR/KWROUS": "injurious"`
  - `"SKWREUR/OUS": "injurious"`
- Adding the following strokes to `bad-habits.json`:
  - `"SKWREUR/OUS": "injurious"`
- Adding the following strokes to `condensed-strokes.json`:
  - `"EUPB/SKWRAOUR/KWROUS": "injurious",`
  - `"SKWREUR/KWROUS": "injurious",`
  - `"SKWRAOUR/OUS": "injurious",`
- In `top-10000-project-gutenberg-words.json`, change:
  - before: `"SKWREUR/OUS": "injurious"`
  - after: `"SKWRAOUR/OUS": "injurious"` (or, if it's better to have a named Plover stroke entry here, I'd propose `"EUPB/SKWRAOUR/OUS": "injurious"`)

**Comment by didoesdigital** [comment]
Goodness! Thanks for this @paulfioravanti . 

Given these exist in the dictionary in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```
"SKWRAOUR": "injury",
"SKWR*EUR": "injury",
"SKWR-R": "injure",
"SKWREUR": "jury",
```

… I'd be keen to lean into `SKWR-R/` or `"SKWRAOUR": "injury",` over `"SKWREUR": "jury",`.

The following suffix strokes also exist:

```
"OUS": "{^ous}",
"WOUS": "{^uous}",
"KWRUS": "{^us}",
"KWROUS": "{^ious}",
```

With this in mind, I'd prefer an entry that uses the suffix entry that best aligns with the letters we have: `"KWROUS": "{^ious}",`

I'm a little puzzled by this part:

![image](https://user-images.githubusercontent.com/2476974/76850482-94916e80-689b-11ea-8c56-b5a90625c580.png)

… as I can see both of those entries in the `main.json`. Am I looking for the wrong thing? Are they the entries you meant to mention?

I think we want to move the entries (including the new Plover ones) using the incorrect suffixes `/KWRUS`, `/OUS` and `/WOUS` to `bad-habits.json`. We might also move `"EUPB/SKWRAOUR/KWROUS": "injurious",` to `bad-habits.json` for redundantly including the "in-" sound in the `EUPB` prefix stroke as well as the `SKWRAOUR` brief stroke.

Overall, I think I prefer `"SKWR-R/KWROUS": "injurious",` as a skeleton brief that matches the entry for the base word, `"SKWR-R": "injure",`

**Comment by paulfioravanti** [comment]
> I can see both of those entries in the main.json. Am I looking for the wrong thing? Are they the entries you meant to mention?

When I looked up "injurious" in vanilla Plover, I got back the following strokes:

```
injurious:
   SKWR*R/WOUS
   SKWREUR/OUS
   SKWR-R/KWRUS
   SKWR*R/KWROUS
   SKWR-R/KWROUS
   SKWREUR/KWROUS
   EUPB/SKWRUR/OUS
   EUPB/SKWRAOUR/OUS
   EUPB/SKWRUR/KWROUS
   EUPB/SKWRAOUR/KWRUS
```

...which does not include (as far as I can see...?):

```
EUPB/SKWRAOUR/KWROUS
```

Sorry, my mistake for adding `"SKWREUR/KWROUS` to the list of strokes, as it _is_ in Plover, but it would seem that `EUPB/SKWRAOUR/KWROUS` is not (I think my eyes glazed over at seeing so many similar strokes). But yes, I agree with moving `EUPB/SKWRAOUR/KWROUS` to `bad-habits.json`.
