### ISSUE TITLE
Stroke for "muscular" missing `H` stroke for "m" sound

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#216]
In the current `dict.json` file, there are the following strokes for "muscular", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PH*UFL/A*R": "muscular",
"PHUBG/HRAR": "muscular",
"PHUFBG/HRAR": "muscular",
"PHUFPBG/HRAR": "muscular",
"PHUS/KAOU/HRAR": "muscular",
"PHUS/KHRAR": "muscular",
"PHUS/KU/HRAR": "muscular",
"PUFBG/HRAR": "muscular",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "muscular" is:

https://github.com/didoesdigital/steno-dictionaries/blob/ef6a38a679db5a27769e0c9e2116f2d02a09165f/dictionaries/top-10000-project-gutenberg-words.json#L7548

`"PUFBG/HRAR": "muscular"` without an `H` stroke to form the beginning "m" sound looks like a mis-stroke to me, so I would like to propose:

- Removing `"PUFBG/HRAR": "muscular"` from `dict.json`
- Adding `"PUFBG/HRAR": "muscular"` to `bad-habits.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"PUFBG/HRAR": "muscular"`
  - after: `"PHUFBG/HRAR": "muscular"`

Some of the other strokes also look a bit strange to me:

```json
"PHUBG/HRAR": "muscular", // no "s"
"PH*UFL/A*R": "muscular" // derivation from "muscle" means too many asterisks?
"PHUFPBG/HRAR": "muscular" // uses PBG "ng" sound?
```

If agreed upon, I'd also propose moving the above three strokes to `bad-habits.json`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. `"PUFBG/HRAR": "muscular"` looks like a misstroke so those changes make sense to me.

`"PHUBG/HRAR": "muscular", // no "s"` also looks like a misstroke to move to `bad-habits.json`.

I'm not sure about `"PH*UFL/A*R": "muscular" // derivation from "muscle" means too many asterisks?` — I'm not sure I understand "too many asterisks" here. It could be aiming for the suffix entry `"A*R": "{^ar}",` 

`"PHUFPBG/HRAR": "muscular" // uses PBG "ng" sound?` also looks off to me.
