### ISSUE TITLE
Possible condensed stroke candidates

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#217]
While doing practice, I thought I had come across some mis-strokes, but when looking up what I thought was a fix in Plover, there were no entries for what I thought would be the "correct" stroke.

So, I'd like to offer up the following strokes for consideration for possible inclusion into the `condensed-strokes.json` dictionary, as strokes that while not in Plover, do output the expected result, and are not currently in the dictionaries:

```json
"KARBG/AOEUZ/-D": "characterized",
"TPEL/OE/SH-P": "fellowship",
"SEUG/TPAOEU/-S": "signifies",
```

**Comment by didoesdigital** [comment]
Awesome! These look great to me @paulfioravanti, thanks for offering these up.

**Comment by paulfioravanti** [comment]
Further to these, I have a couple more potential condenses strokes:

```
"STRUBGT/EUF": "instructive"
"SAOER/KWRUS/-PBS": "seriousness"
```

Personally, I think the vowel accents on these two strokes read better than their counterparts in the Gutenberg dictionaries:

https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/top-10000-project-gutenberg-words.json#L8584

https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/top-10000-project-gutenberg-words.json#L8728

Happy to change them in a PR that covers this issue, or, also happy to leave as is if condensed strokes should be avoided in the Gutenberg dictionary.

**Comment by paulfioravanti** [comment]
Another condensed stroke, "violated" with the long "ī" sound:

```json
"SRAOEULT/-D": "violated"
```

Current Gutenberg stroke:

https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/top-10000-project-gutenberg-words.json#L8978

**Comment by didoesdigital** [comment]
Hey @paulfioravanti, I changed `"SAOER/KWRUS/-PBS": "seriousness"` to `"SAOER/KWROUS/-PBS": "seriousness",` adding an `O` to match `"KWROUS": "{^ious}",` while resolving conflicts. I'll need to follow up for these entries too:

```
"SAOER/KWRUS": "serious",
"SAOER/KWRUS/HREU": "seriously",
"SAOER/KWRUS/TPHES": "seriousness",
```

Sounds good to update instructive, seriousness, and violated in Top 10000 Project Gutenberg words.

**Comment by didoesdigital** [comment]
FYI fixed serious* in https://github.com/didoesdigital/steno-dictionaries/commit/3a9dede6c8589143d0333e5a9c31d57f67a6df5b

**Comment by didoesdigital** [comment]
FYI updated instructive and violated in 814001d
