### ISSUE TITLE
Stroke for "Sophia" missing `E` stroke for "ē" sound

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#218]
In the current `dict.json` file, there are the following strokes for "Sophia", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"SOE/TPAO/KWRA": "Sophia",
"SOE/TPAOE/KWRA": "Sophia",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "Sophia" is:

https://github.com/didoesdigital/steno-dictionaries/blob/483428943a089b18e6f3f3a7a4e9b6e265328a65/dictionaries/top-10000-project-gutenberg-words.json#L7663

`"SOE/TPAO/KWRA": "Sophia"` without an `E` stroke for the "ē" sound in "So*phi*a" looks like a mis-stroke to me, so I would like to propose:

- Removing `"SOE/TPAO/KWRA": "Sophia"` from `dict.json`
- Adding `"SOE/TPAO/KWRA": "Sophia"` to `bad-habits.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"SOE/TPAO/KWRA": "Sophia"`
  - after: `"SOE/TPAOE/KWRA": "Sophia"`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti , these changes look great. Your suggested entry also aligns with `"SOE/TPAOE": "Sophie",`

**Comment by paulfioravanti** [comment]
Another one for this list as it's a name that needs an "ē" sound:

In the current `dict.json` file, there are the following strokes for "Ulysses", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"AOU/HREUS/AOES": "Ulysses",
"AOU/HREUS/ES": "Ulysses",
"AOU/HREUS/EUS": "Ulysses",
"AOUL/HREUS/SAOES": "Ulysses",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "Ulysses" is:

https://github.com/didoesdigital/steno-dictionaries/blob/0cfbdf29012d1fb7359483fb866197626bc7e089/dictionaries/top-10000-project-gutenberg-words.json#L7976

I had to look up the [pronunciation of Ulysses](https://www.oxfordlearnersdictionaries.com/us/pronunciation/english/ulysses), and it would seem that the "e" is an "ē" sound, which would mean, that the following strokes could be considered mis-strokes:

- `"AOU/HREUS/ES": "Ulysses`
- `"AOU/HREUS/EUS": "Ulysses"`

So, I would like to propose:

- Removing `"AOU/HREUS/ES": "Ulysses` and `"AOU/HREUS/EUS": "Ulysses"` from `dict.json`
- Adding `"AOU/HREUS/ES": "Ulysses` and `"AOU/HREUS/EUS": "Ulysses"` to `bad-habits.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"AOU/HREUS/ES": "Ulysses`
  - after: `"AOU/HREUS/AOES": "Ulysses",`

**Comment by didoesdigital** [comment]
Thanks, @paulfioravanti . Just noting that there is a suffix entry for `"ES": "{^es}",`. As `AOU/HREUS` doesn't translate to anything sensible, I'm happy to go ahead with the changes as you described. If it had translated to "Ulyss` or similar, I might have been inclined to leave `"AOU/HREUS/ES": "Ulysses"` using the suffix stroke.
