### ISSUE TITLE
Stroke for "theatrical" has extraneous `F` stroke

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#219]
In the current `dict.json` file, there are the following strokes for "theatrical":

```json
"THAO*ERT/K-L": "theatrical",
"THAOEFRT/K-L": "theatrical",
"THRAOERT/K-L": "theatrical",
"THAO*EURT/K-L": "theatrical",
"THAOE/AT/K-L": "theatrical",
"THAOE/TREUBG/AL": "theatrical",
"THAOET/REUBG/A*L": "theatrical",
"THRAOET/REUBG/A*L": "theatrical",
"THAOE/AT/REU/KAL": "theatrical",
"THAOE/AT/REUBG/KAL": "theatrical",
```

All of these strokes which are valid in when stroked in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), except for the final entry in this list, `"THAOE/AT/REUBG/KAL": "theatrical",`, which does not seem to be a named entry in the default Plover dictionaries, though it still outputs "theatrical" as expected.

Also, it would seem that Plover has added `THAOERT/K-L` as a named stroke for "theatrical".

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "theatrical" is:

https://github.com/didoesdigital/steno-dictionaries/blob/0cfbdf29012d1fb7359483fb866197626bc7e089/dictionaries/top-10000-project-gutenberg-words.json#L8034

The `F` stroke in `"THAOEFRT/K-L": "theatrical"` looks extraneous to me, especially since this stroke is the only one of the set to use it, so, I'd probably consider it a mis-stroke.

So, given this, and the situation with new strokes, I would like to propose:

- Adding `"THAOERT/K-L": "theatrical"` to `dict.json`
- Removing `"THAOEFRT/K-L": "theatrical"` and `"THAOE/AT/REUBG/KAL": "theatrical",` from `dict.json`
- Adding `"THAOEFRT/K-L": "theatrical"` to `bad-habits.json`
- Adding `"THAOE/AT/REUBG/KAL": "theatrical",` to `condensed-strokes.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"THAOEFRT/K-L": "theatrical"`
  - after: `"THAOERT/K-L": "theatrical"`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti . That mostly sounds good except I can see `"THAOE/AT/REUBG/KAL": "theatrical",` on line 114930 of [`main.json`](https://github.com/openstenoproject/plover/blob/master/plover/assets/main.json). Am I missing something? Is it possible whatever you're using to look up entries is not showing all of them?

**Comment by paulfioravanti** [comment]
Thanks for picking that up, @didoesdigital. So, when I run a search for "theatrical" on Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), I get:

```
theatrical:
   THAOERT/K-L
   THAO*ERT/K-L
   THAOEFRT/K-L
   THRAOERT/K-L
   THAO*EURT/K-L
   THAOE/AT/K-L
   THAOE/TREUBG/AL
   THAOET/REUBG/A*L
   THRAOET/REUBG/A*L
   THAOE/AT/REU/KAL
```

You're right about it being in `main.json`, though, so I wonder what happened. Perhaps it was added in after the latest release was cut...? Regardless, in the PR I do for this issue, I'll leave `"THAOE/AT/REUBG/KAL": "theatrical"` as-is.
