### ISSUE TITLE
Stroke for "transition" missing an `R` stroke

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#220]
In the current `dict.json` file, there are the following strokes for "transition":

```json
"TAPBS/EUGS": "transition",
"TRAPB/SEUGS": "transition",
"TRAPBS/EUGS": "transition",
"TRAPBZ/EUGS": "transition",
"TRA*PBS/EUGS": "transition",
"TRAPB/S*EUGS": "transition",
"TRAPBS/SEUGS": "transition",
"TRA*PBS/SEUGS": "transition",
```

All of these strokes which are valid in when stroked in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), except for the final entry in this list, `"TRA*PBS/SEUGS": "transition"`, which does not seem to be a named entry in the default Plover dictionaries, though it still outputs "transition" as expected.

Also, it would seem that Plover has added the following strokes for "transition":

```json
"TREUGS": "transition"
"STREUGS": "transition"
"TRAPBGS": "transition"
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "transition" is:

https://github.com/didoesdigital/steno-dictionaries/blob/0cfbdf29012d1fb7359483fb866197626bc7e089/dictionaries/top-10000-project-gutenberg-words.json#L7999

`"TAPBS/EUGS": "transition"` without an `R` stroke looks like a mis-stroke to me.

So, given this, and the situation with new strokes, I would like to propose:

- Adding the following strokes to `dict.json`:
  - `"TREUGS": "transition"`
  - `"STREUGS": "transition"`
  - `"TRAPBGS": "transition"`
- Removing `"TAPBS/EUGS": "transition"` from `dict.json`
- Adding `"TAPBS/EUGS": "transition"` to `bad-habits.json`
- Adding `"TRA*PBS/SEUGS": "transition"` to `condensed-strokes.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"TAPBS/EUGS": "transition"`
  - after: `"TREUGS": "transition"` (this looks like a good place to use a single-stroke entry, and my preference would be for this one)

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti . 

There were a few other changes needed in there so I made those: https://github.com/didoesdigital/steno-dictionaries/compare/f8d0d1f9ae723a0e98d92ca31ae032e77c008820...286b3c1d35021ee7ef705256c438c2b137012d14

I didn't add the brief for `"STREUGS": "transition"`. There are no other entries starting with `STREU` that produce words starting with "t" so I sent that entry straight to `bad-habits.json`
