### ISSUE TITLE
Stroke for "harmonious" missing beginning `H` stroke

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#221]
In the current `dict.json` file, there are the following strokes for "harmonious", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"AR/PHOEPB/KWROUS": "harmonious",
"HAR/PHOEPB/KWROUS": "harmonious",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "harmonious" is:

https://github.com/didoesdigital/steno-dictionaries/blob/0cfbdf29012d1fb7359483fb866197626bc7e089/dictionaries/top-10000-project-gutenberg-words.json#L8004

`"AR/PHOEPB/KWROUS": "harmonious"` without a beginning `H` stroke looks like a mis-stroke to me, so I would like to propose:

- Removing `"AR/PHOEPB/KWROUS": "harmonious"` from `dict.json`
- Adding `"AR/PHOEPB/KWROUS": "harmonious"` to `bad-habits.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"AR/PHOEPB/KWROUS": "harmonious"`
  - after: `"HAR/PHOEPB/KWROUS": "harmonious"`

**Comment by didoesdigital** [comment]
Sounds good to me! Thanks @paulfioravanti
