### ISSUE TITLE
Issue with "-ily" suffix in "mightily"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#222]
In the current dictionaries, there are entries for the following stroke for "mightily":

https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/nouns.json#L125

https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/top-10000-project-gutenberg-words.json#L8149

When I try and stroke this using Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), it outputs "mightly".

I couldn't seem to find an "-ily" suffix entry in the dictionaries or Plover (I may have missed it...?), but, playing around, I found out that making "mighty" before "mightily" got me what I wanted with the following stroke: `PHAOEUT/KWREU/HREU`.

There is no Plover entry for "mightily", so I would like to propose:

- Adding `"PHAOEUT/KWREU/HREU": "mightily"` to `condensed-strokes.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"PHAOEUT/HREU": "mightily"`
  - after: `"PHAOEUT/KWREU/HREU": "mightily"`
- (Maybe also) In `nouns.json` change:
  - before: `"PHAOEUT/HREU": "mightily"`
  - after: `"PHAOEUT/KWREU/HREU": "mightily"`

**Comment by didoesdigital** [comment]
Nice one @paulfioravanti !

Using `"SKWREU": "{^i}"` instead of `"KWREU": "{^y}"`, let's make it `"PHAOEUT/SKWREU/HREU": "mightily"`, in `top-10000-project-gutenberg-words.json` and `nouns.json`

**Comment by paulfioravanti** [comment]
Thanks, @didoesdigital! I'll add `"PHAOEUT/SKWREU/HREU": "mightily"` into `condensed-strokes.json` as well.
