### ISSUE TITLE
Entry for "abuse" has extraneous `S` stroke

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#223]
In the current `dict.json` file, there are the following strokes for "abuse", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"A/PWAOUS": "abuse",
"A/PWAUS": "abuse",
"A/SPWAOUS": "abuse",
"SPWAOUS": "abuse",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the strokes used for "abuse" and "abuses" are:

https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/top-10000-project-gutenberg-words.json#L4474

https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/top-10000-project-gutenberg-words.json#L8425

`"SPWAOUS": "abuse"` with a leading `S` looked a bit strange to me, and when I looked up Plover, I found two strokes for "abuse" that are not in the current dictionaries:

```
abuse:
   PWAOUS
   PWAO*US
```

The first one, `PWAOUS`, seems like the most appropriate single-stroke entry to me, so I would like to propose:

- Adding the following strokes to `dict.json`:
  - `"PWAOUS": "abuse"`
  - `"PWAO*US": "abuse"`
- Removing the following strokes from `dict.json`:
  - `"SPWAOUS": "abuse"`
  - `"A/SPWAOUS": "abuse"`
- Adding the following strokes from `bad-habits.json`:
  - `"SPWAOUS": "abuse"`
  - `"A/SPWAOUS": "abuse"`
- Changing the following strokes in `top-10000-project-gutenberg-words.json`:
  - "abuse"
    - before: `"SPWAOUS": "abuse"`
    - after: `"PWAOUS": "abuse"`
  - "abuses"
    - before: `"SPWAOUS/-S": "abuses"`
    - after: `"PWAOUS/-S": "abuses"`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti , these changes look great!
