### ISSUE TITLE
PH*PB for "mountain"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#26]
It seems that Plover has an entry of `PH*PB` for "mountain", which I think is good since it's easy to stroke and remember. However, it doesn't seem to gel with other current mountain-related briefs in `dict.json` like the following, that use the stroke of `PHOUPB/TAEUPB`, or some variation of it, for "mountain":

```
"PHOUPB/TAEUPB/SAO*EUD": "mountainside",
"PHOUPB/TAEUPB/SAOEUD": "mountainside",
"PHOUPB/TAEUPB/TKAOU": "Mountain Dew",
"PHOUPB/TAEUPB/TO*P": "mountaintop",
"PHOUPB/TAEUPBDZ": "mountainside",
"PHOUPB/TAEUPBS": "mountains",
"PHOUPB/TPHOUS": "mountainous",
```

So, my question is, is it worth adding the `PH*PB` as a brief for only the _standalone_ word "mountain"? It doesn't seem to be compose-able, so you can't stroke, for example, `"PH*PB/SAO*EUD": "mountainside"` since there will be a space between "mountain" and "side", so that would be a potential strike against it. Any particular opinions for or against `PH*PB`?

**Comment by didoesdigital** [comment]
Thanks for raising this, @paulfioravanti. It's a great question, and I have mixed thoughts on these issues.

In the past, some people in the community have expressed resentment towards Typey Type for failing to teach them the best "set" of strokes like that. That gives us a decent signal that it would be useful to leave out `PH*PB`.

On the other hand, if "mountain" as a standalone word is extremely common while its friends like "Mountain Dew" rarely arise, I'd be grateful for learning the brief version of it.

On the balance, I would guess the "set" would be more useful to Typey Type's audience. If you're experienced enough to know you need a brief for "mountain" after having learned `"PHOUPB/TAEUPB": "mountain"`, you can probably find up or come up with a brief that works for you when it's the right time in your steno journey. What do you think?

**Comment by didoesdigital** [comment]
It might be a case-by-case issue depending on the frequency of a standalone word compared to the rest of the words in its set.

**Comment by paulfioravanti** [comment]
> If you're experienced enough to know you need a brief for "mountain" after having learned "PHOUPB/TAEUPB": "mountain", you can probably find up or come up with a brief that works for you when it's the right time in your steno journey.

Makes sense to me! Since I'm still at the beginning of my steno journey, I would wager it makes more sense to build muscle memory for `PHOUPB/TAEUPB` and see about more condensed briefs later. Thanks for your thoughts!
