### ISSUE TITLE
Unknown stroke for "appellation"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#268]
In the dictionaries, there is the following stroke entry for "appellation":

https://github.com/didoesdigital/steno-dictionaries/blob/fb0fd2fb03b97163c8147363a66ad54130b8e427/dictionaries/nouns.json#L202

https://github.com/didoesdigital/steno-dictionaries/blob/fb0fd2fb03b97163c8147363a66ad54130b8e427/dictionaries/top-10000-project-gutenberg-words.json#L9929

However in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), this outputs as "appealation".

I couldn't figure out a condensed stroke to make this work, so I ended up just fingerspelling it in Typey Type to progress forward. What would be the best stroke to change this to?

**Comment by didoesdigital** [comment]
Thanks for flagging this @paulfioravanti ! I used `"KWROPB": "{^ion}",` to fix it in https://github.com/didoesdigital/steno-dictionaries/commit/88cb048df3b25dcc83f9d6c1cf26d3dcd5b2b846
