### ISSUE TITLE
S*ELTD vs SELTD for "settled"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#28]
The stroke entry for the word "settled" in Plover and Typey Type is `S*ELTD`. The word "settled" can also be stroked more easily without the asterisk as `SELTD` (which I found out by accident).

However, there is no specified entry for this stroke in any dictionary in Typey Type or Plover. Is there a reason for this that you can think of? If not, would this entry be worth adding to the Typey Type dictionaries as an improvement on the Plover entry?

**Comment by didoesdigital** [comment]
@paulfioravanti It looks like `SELTD` is using [Plover's suffix keys](https://github.com/openstenoproject/plover/blob/685bd3373dcf19817f59070274a33457ff145701/plover/system/english_stenotype.py#L13), [Plover's orthography English rules](https://github.com/openstenoproject/plover/blob/685bd3373dcf19817f59070274a33457ff145701/plover/system/english_stenotype.py#L64-L65), and [Plover's orthography translation](https://github.com/openstenoproject/plover/blob/685bd3373dcf19817f59070274a33457ff145701/plover/formatting.py#L754-L776).

The suffix key `-D` will automatically append "ed" using `"-D": "{^ed}",` when tucked into an existing entry. Given the entry, `"SELT": "settle"`, I would expect adding "D" to produce something like `settle{^ed}`.

Then, using [Plover's orthography rules](https://github.com/openstenoproject/plover/blob/685bd3373dcf19817f59070274a33457ff145701/plover/system/english_stenotype.py#L64-L65), the second "e" is removed to give us "settled" as intended.

[I've added some explicit entries for settled, settling, and settles](https://github.com/didoesdigital/steno-dictionaries/pull/29) to improve look ups in Typey Type. 

Generally I try to limit the `condensed-strokes.json` dictionary to entries that work from a combination of existing entries like "TEFT" and "TEFT/-G" where "TEFT" exactly matches "test" and "-G" is "ing". In this case, "settled" *depends on the orthography rules* for English and couldn't work by strokes alone. I think this is near enough though.

**Comment by paulfioravanti** [comment]
Thanks for the detailed explanation, @didoesdigital. That helps a lot!
