### ISSUE TITLE
`HRES` vs `-LS` for "-less"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#294]
I recently came across the outline `TPRAOUT/HRES` for "fruitless". This is the outline used in Plover [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33).

However, the `TPRAOUT/-LS` outline also outputs the "fruitless" as expected. I was considering submitting this as a potential condensed stroke, but just wanted to check and see if there was any steno rule I didn't know about regarding using `HRES` vs `-LS` for the "-less" suffix that favoured one over the other as a general rule or in certain circumstances.

**Comment by didoesdigital** [comment]
Hmm, no other rules that I can think of. Given these entries,

```
"HRES": "less",
"-LS": "{^less}",
```

… `"TPRAOUT/-LS": "fruitless"` looks good to me.
