### ISSUE TITLE
Dictionary entries for "toss"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#30]
I noticed that in the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "toss" is `TOSZ`, while in `dict.json` it is `TO*S`.

In the Plover dictionary for release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), "toss" can be stroked as `TOS`, which is currently reflected in other dictionary entries in `dict.json` using "toss"-related words like:

```json
"TOS/-D": "tossed",
"TOS/-G": "tossing",
"TOS/-S": "tosses",
```

However, in `dict.json`, the entry for `TOS` is `"TOS": "{^s to}"`.

So, my questions are:

- Is the `"TOS": "{^s to}"` entry still correct?
- If it is not, is it worth attempting to standardise "toss"-related entries to use the easiest-to-stroke `TOS` (versus `T*OS` or `TOSZ`). If so, I'm happy to make a PR for this.

**Comment by didoesdigital** [comment]
@paulfioravanti `"TOS": "{^s to}"` must have been in an old version of Plover dictionary. 

Standardising on `TOS` sounds fine to me. A lot of words with "ss" use `SZ`, though many of those also have a `S` only option, like `"PHOSZ": "moss"` and ``"PHOS": "moss". `SZ` might be used to distinguish 1 "s" and 2 like `"PWUS": "bus"` and `"PWUSZ": "buss"`. Before settling on `TOS`, I would check words starting with `TOS/` to see if that would be a common source of conflicts, but it looks like there are only a few entries starting that way so `"TOS": "toss"` seems safe to use.

**Comment by paulfioravanti** [comment]
>  it looks like there are only a few entries starting that way so "TOS": "toss" seems safe to use.

Yeah, I just had a look, and it seems that way to me, too, so I'll send through a PR.
