### ISSUE TITLE
Question about outline for "drunkenness"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#300]
Using Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s search function to look up outlines for "drunkenness" returns:

```
drunkenness:
   TKRUPB/KEPB/*PBS
   PWRUPB/KEPB/TPHES
```

The current `dict.json` file has only the `"PWRUPB/KEPB/TPHES": "drunkenness"` entry, while `TKRUPB/KEPB/*PBS` is marked as a mis-stroke:

https://github.com/didoesdigital/steno-dictionaries/blob/cd9048411754dddb3c3e043134b2f8e85f952908/dictionaries/misstrokes.json#L3282

This seems strange to me as `TKRUPB/KEPB/*PBS` sounds like a more accurate pronunciation match than `PWRUPB/KEPB/TPHES`'s "brunkenness".

I was going to submit a PR with a condensed stroke proposal for `TKRUPB/KEPB/PBS`, since:

- `TKRUPB/KEPB` outputs to "drunken"
- it uses the `"-PBS": "{^ness}"` suffix, removing the asterisk

But, if `TKRUPB/KEPB/*PBS` is considered a mis-stroke, then it looks like I must be missing something. What rule(s) are the outlines for "drunkenness" following in this case?

**Comment by didoesdigital** [comment]
Thanks for writing this up @paulfioravanti .

`PWRUPB/KEPB/TPHES` is a misstroke 👍

Searching for why `TKRUPB/KEPB/*PBS` was deleted using `git log -S'"TKRUPB/KEPB/*PBS": "drunkenness",' -- dictionaries/dict.json --follow-parent` reveals that it was deleted in https://github.com/didoesdigital/steno-dictionaries/commit/f6d805163ab252124fc79e2f11e3a014f5986df7  where I removed misstrokes for "drunk-" words missing `*` for the "nk" sound, following the Plover theory for [`*PBG`: the 'nk' cluster, as in 'mink', 'honk', and 'prank'](https://sites.google.com/site/learnplover/lesson-3-english-sounds/3e-compound-clusters#TOC-Common-Compound-Clusters).

Given that, I think we could add condensed stroke entries for `"TKR*UPBG/*EPB/-PBS": "drunkenness"` using all the theoretically best phonetic keys and suffixes and `"TKRUPB/KEPB/-PBS": "drunkenness",` as a compromise leaning on the mostly phonetic entry `"TKRUPB/KEPB": "drunken",`. 

What do you think @paulfioravanti ?

**Comment by paulfioravanti** [comment]
Sounds good to me. Assuming that I understood everything correctly, I'll submit a PR that:

- marks `PWRUPB/KEPB/TPHES` as a mis-stroke
- adds `TKR*UPBG/*EPB/-PBS` and `TKRUPB/KEPB/-PBS` as condensed strokes
- prefers `TKRUPB/KEPB/-PBS` in the Gutenberg dictionary.
