### ISSUE TITLE
Issue with outline for "madam"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#317]
Using Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s search function to look up outlines for "madam" returns:

```
Madam:
   PHAD/APL
   PHA*D/APL
```

Note that both entries are for uppercase "Madam".

The various dictionary files, including `dict.json`, would seem to use `PHAD/APL` for lowercase "madam" and `PHA*D/APL` for uppercase "Madam", yet this conflicts with Plover:

https://github.com/didoesdigital/steno-dictionaries/blob/6fcda7395ef4b30925638d729ec5b53305911a81/dictionaries/proper-nouns.json#L115-L116

https://github.com/didoesdigital/steno-dictionaries/blob/6fcda7395ef4b30925638d729ec5b53305911a81/dictionaries/top-10000-project-gutenberg-words.json#L3894

https://github.com/didoesdigital/steno-dictionaries/blob/6fcda7395ef4b30925638d729ec5b53305911a81/dictionaries/misstrokes.json#L1989

I'm assuming that these current entries should be changed to both be uppercase "Madam", but should a new fingerspelling entry be added for lowercase "madam", particularly if that's the intention in the Gutenberg dictionary? Or, is there another outline that will stroke lowercase "madam" as intended?

**Comment by didoesdigital** [comment]
I can't think of anything good to stroke the lowercase madam as intended, e.g. there's no suffix for "^am" to pair with "mad". There's also no standardised outline for lower casing the next word like [`"HRO*ER":"{>}",`](https://github.com/didoesdigital/steno-dictionaries/blob/master/dictionaries/plover-use.json#L22) that I use. I guess fingerspelling entry in condensed strokes dict? 😭

**Comment by paulfioravanti** [comment]
> I guess fingerspelling entry in condensed strokes dict? 😭

Yep, looks like that'll have to do for now 😞 I'll put in a PR.
