### ISSUE TITLE
`AG/KHUR` for "agriculture" appears in Typey Type

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#339]
While practicing on Typey Type, `AG/KHUR` came up for "agriculture". Looking up Plover for a possibly better outline, I found `AG/KULT`, which gels with me better. I was going to submit a PR that changes the Gutenberg dictionary to use `AG/KULT` (and hence have that used in Typey Type), but it would seem that it's already being used:

https://github.com/didoesdigital/steno-dictionaries/blob/039efe4bdfd806d50703c929f969545a843f4877/dictionaries/top-10000-project-gutenberg-words.json#L5917

I thought that Typey Type in general sources from the Gutenberg dictionary, but in this case, is it sourcing this outline from the shortest outline with the highest alphabetical order in `dict.json`?

**Comment by paulfioravanti** [comment]
I've just seen the same issue with `"KORT/KWROUS": "courteous"` appearing with Typey Type, yet the Gutenberg entry has a "more correct" outline of:

https://github.com/didoesdigital/steno-dictionaries/blob/b1753226e231746366af1c434503cf303ae30944/dictionaries/top-10000-project-gutenberg-words.json#L6149

(I was considering sending a PR to change this to `KURT/KWRUS`, but I see it's already considered a mis-stroke)

https://github.com/didoesdigital/steno-dictionaries/blob/b1753226e231746366af1c434503cf303ae30944/dictionaries/misstrokes.json#L1689

**Comment by paulfioravanti** [comment]
Same issue also with seeing `"SKWRUPBG/*L": "jungle"` in Typey Type, yet Gutenberg also has what I consider to be a better entry of:

https://github.com/didoesdigital/steno-dictionaries/blob/b1753226e231746366af1c434503cf303ae30944/dictionaries/top-10000-project-gutenberg-words.json#L6306

**Comment by didoesdigital** [comment]
Hmm, are you using the experimental setting to show steno hints on the fly? Does changing that setting give you the expected strokes? https://github.com/didoesdigital/typey-type/issues/6#issuecomment-596300356

**Comment by paulfioravanti** [comment]
I do have that setting, so I've now cleared it out for now. If the issue ends up persisting, I'll follow up in the Typey Type repo, since this problem is not related specifically to the dictionaries. Thanks, @didoesdigital!

**Comment by didoesdigital** [comment]
@paulfioravanti I've found something in the (not open-source) static lesson generator project that builds the Typey Type dictionary that I need to change, so don't worry about filing the issue on the Typey Type repo. I'll go ahead and get that sorted. It's surfaced some other tweaks to make in the dictionaries so I'll push those out together soon.

Thanks for flagging these.

**Comment by didoesdigital** [comment]
@paulfioravanti  I ended up changing courteous to `"KORT/KWRO*US": "courteous"` to use the suffix `"KWRO*US": "{^eous}",` and to be consistent with `"KORT": "court"` and not `"KURT": "curt",`

**Comment by didoesdigital** [comment]
@paulfioravanti latest changes should properly show Gutenberg entries.

![image](https://user-images.githubusercontent.com/2476974/79686937-43eca700-8287-11ea-8004-6542f3d7474a.png)
