### ISSUE TITLE
Potential meta-issue with outline for "seventy-five"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#372]
Currently, all the dictionaries, including Gutenberg, have the correct Plover outline of "seventy-five": `SEFPBT/TPAOEUF`. However, in Typey Type, the outline hint shown was `SEFPBT/TPEUF`, which outputs "seventy five" without the dash (not to be confused with `SEFPBT/H-PB/TPEUF`, which _is_ in the `condensed-strokes.json` dictionary, but this is not the outline that gets shown in Typey Type).

This is probably a bit of a meta-issue for the dictionaries, and more to do with Typey Type(?), so if that's the case, I'm happy to transfer the issue over to the Typey Type repo.

**Comment by didoesdigital** [comment]
Quite right, there was a hard-coded on the static lesson generator fix incorrectly using that other outline. I've updated the hard-coded patch, continuing to live with that until I can make it redundant.

I've now fixed "seventy-five", "twenty-five", "well-known", and "self-control"
