### ISSUE TITLE
Issue with some incorrect outlines for words not in Plover

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#373]
I've found a few words shown in Typey Type that do not currently have outlines in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), and I couldn't figure out condensed strokes for them:

- **"verdure"**

https://github.com/didoesdigital/steno-dictionaries/blob/f80c7dbd1b58c56c4d9acb0a76d0810f9d0e61d6/dictionaries/top-10000-project-gutenberg-words.json#L9661

This entry looks like it comes from `nouns.json`:

https://github.com/didoesdigital/steno-dictionaries/blob/f80c7dbd1b58c56c4d9acb0a76d0810f9d0e61d6/dictionaries/nouns.json#L185

Stroking `SRER/SKWRUR` outputs "ver jury".

- **"parapet"**

https://github.com/didoesdigital/steno-dictionaries/blob/f80c7dbd1b58c56c4d9acb0a76d0810f9d0e61d6/dictionaries/top-10000-project-gutenberg-words.json#L9662

This entry also comes from `nouns.json`:

https://github.com/didoesdigital/steno-dictionaries/blob/f80c7dbd1b58c56c4d9acb0a76d0810f9d0e61d6/dictionaries/nouns.json#L186

Stroking `PRA/PET` outputs "pra pet".

- **"Somerset"**

https://github.com/didoesdigital/steno-dictionaries/blob/f80c7dbd1b58c56c4d9acb0a76d0810f9d0e61d6/dictionaries/top-10000-project-gutenberg-words.json#L9690

This entry seems to come from `proper-nouns.json`:

https://github.com/didoesdigital/steno-dictionaries/blob/f80c7dbd1b58c56c4d9acb0a76d0810f9d0e61d6/dictionaries/proper-nouns.json#L72

Stroking `SOPL/ER/SET` outputs "some erset".

To get through these three entries in Typey Type, I just finger-spelled them. Should finger-spelled entries for these three words be added to the dictionaries (for now?), or are there other outlines you can think of that work with vanilla Plover?

**Comment by paulfioravanti** [comment]
Adding to this list:

- **"hast"**

https://github.com/didoesdigital/steno-dictionaries/blob/29f938657238f56d03940ea05ac767635d5a808b/dictionaries/top-10000-project-gutenberg-words.json#L1326

This entry seems to come from:

https://github.com/didoesdigital/steno-dictionaries/blob/29f938657238f56d03940ea05ac767635d5a808b/dictionaries/nouns.json#L166

Stroking `HA*FT` outputs "HA*FT" as-is

**Comment by didoesdigital** [comment]
Yep, I think fingerspelling will have to do. I've just closed https://github.com/didoesdigital/steno-dictionaries/issues/115 so things may have moved.
