### ISSUE TITLE
Typey Type using personal Di briefs?

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#423]
While doing exercises in Typey Type, I came across this entry for "extends":

<img width="175" alt="Typey_Type___Lesson__Top_10000_Project_Gutenberg_words" src="https://user-images.githubusercontent.com/543366/82728257-9ca1da80-9d32-11ea-9b35-f2e048fb84ab.png">

Stroking it outputted "ST*EPBDZ" as-is for me, so when I looked up the dictionaries to see the outlines used for "extends", I found:

**`dict.json`**

```
"EBGS/TEPBDZ": "extends"
```

https://github.com/didoesdigital/steno-dictionaries/blob/47fabaf8affaa8fdb472c02d5b97232396d2afb7/dictionaries/top-10000-project-gutenberg-words.json#L6865

https://github.com/didoesdigital/steno-dictionaries/blob/47fabaf8affaa8fdb472c02d5b97232396d2afb7/dictionaries/di-briefs.json#L27

This would lead me to suppose that Typey Type is using Di personal dictionaries to generate its lessons, which I'm wagering isn't desired due to their subjective nature. 

If this issue is more to do with Typey Type than these dictionaries, I'm happy to close this and move the issue over to the Typey Type repo.

**Comment by didoesdigital** [comment]
I think this was fixed in https://github.com/didoesdigital/steno-dictionaries/commit/81c320088b19673e5dd897037a6a90bef7b1c3f0 ?

**Comment by paulfioravanti** [comment]
Hmmm...perhaps I just need to refresh my browser to get those new changes...? It certainly does look like those changes have already been made, so I'll close this issue, and if I see it again, I'll re-open.

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti . That makes sense, it was a recent change so Typey Type usually needs a hard refresh to get the latest.
