### ISSUE TITLE
Issue with "mare", "mayor", and "Mayor"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#43]
In Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), it would seem that there is no entry for "mare", but there are two entries in the dictionaries:

https://github.com/didoesdigital/steno-dictionaries/blob/8f0c575a78fc1d204834f56cc61679a969147867/dictionaries/nouns.json#L111
https://github.com/didoesdigital/steno-dictionaries/blob/cd65df90bda21bfbee4523ab25f973b7f2b8369b/dictionaries/top-10000-project-gutenberg-words.json#L6245

The entry for the stroke `PHAEUR` resolves to "mayor" in Plover, so having a look at the current Typey-Type dictionary strokes for "mayor", I can see:

https://github.com/didoesdigital/steno-dictionaries/blob/cd65df90bda21bfbee4523ab25f973b7f2b8369b/dictionaries/top-10000-project-gutenberg-words.json#L7694
https://github.com/didoesdigital/steno-dictionaries/blob/39943572e8837e031b6efdb81d995ab26c4b64e1/dictionaries/top-10000-english-words.json#L4553

but, the stroke `PHA*EUR` resolves to capitalised "Mayor" in Plover.

So, I guess I'd have the following questions:

- Since "mare" is in the Project Gutenberg dictionaries, I assume you want to keep it, so should the stroke for that entry perhaps be changed into the fingerspelling of "mare", and a new `"PHAEUR": "mayor"` entry added to `dict.json`?
- For the `"PHA*EUR": "mayor"` entries, should the stroke be changed to `PHAEUR` for "mayor", or should the entry be changed to be capitalised "Mayor"?

**Comment by didoesdigital** [comment]
> Since "mare" is in the Project Gutenberg dictionaries, I assume you want to keep it, so should the stroke for that entry perhaps be changed into the fingerspelling of "mare", and a new "PHAEUR": "mayor" entry added to dict.json?

Fingerspelling "mare" sounds good to me. Perhaps in `condensed-strokes.json` instead of `dict.json`.

> For the "PHA*EUR": "mayor" entries, should the stroke be changed to PHAEUR for "mayor", or should the entry be changed to be capitalised "Mayor"?

Let's change it to `PHAEUR` for "mayor".
