### ISSUE TITLE
Confusion over outline for "ab" in Gutenberg dictionary

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#434]
In the Gutenberg dictionary, the outline used for "ab" is:

https://github.com/didoesdigital/steno-dictionaries/blob/47fabaf8affaa8fdb472c02d5b97232396d2afb7/dictionaries/top-10000-project-gutenberg-words.json#L7390

However, this comes from a personal Di dictionary entry:

https://github.com/didoesdigital/steno-dictionaries/blob/47fabaf8affaa8fdb472c02d5b97232396d2afb7/dictionaries/di-nouns.json#L292

The only other entry I can find for "ab" is `"AB": "{ab^}"` in `dict.json`, but I'm wagering that the Gutenberg entry is not meant to be the ab- prefix...? If it is, then I'm happy to submit a PR changing the entry to the prefix. If not, then I'm assuming that the fingerspelling would be most appropriate here. What do you think?

**Comment by didoesdigital** [comment]
Fingerspelling seems like the best path for now

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti 👏
