### ISSUE TITLE
Issue with stroke for "com"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#44]
Currently in the dictionaries, there are entries for `"KRO*PL": "com"` in:

https://github.com/didoesdigital/steno-dictionaries/blob/39943572e8837e031b6efdb81d995ab26c4b64e1/dictionaries/top-10000-english-words.json#L1113
and in `dictionaries/dict.json:42641`

However, in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), there is no entry for lowercase "com".

The stroke `KRO*PL`, as well as `KROPL`, resolve to `{^.com}`. There is are entries for `KROPL` in these dictionaries:

https://github.com/didoesdigital/steno-dictionaries/blob/f98e522fd3637a7fe8b9f3cdf79544b15b25ff1c/dictionaries/top-level-domains.json#L3
and in `dictionaries/dict.json:42877`

There is also an entry in the UX-Design dictionary for `KROPL` as the standalone string  `".com"`, though I'm guessing this is a conflict with the other dictionaries, and is now incorrect:

https://github.com/didoesdigital/steno-dictionaries/blob/f98e522fd3637a7fe8b9f3cdf79544b15b25ff1c/dictionaries/ux-design.json#L54

The only entry in Plover that is closest to a "com" standalone string is the uppercased version: `"KO*PL/KO*PL": "COM"`.

Based on this what changes should be made to the dictionaries? I'm assuming that:

- `"KROPL": ".com"` in the UX dictionary should be changed to `"KROPL": "{^.com}"`
- `"KO*PL/KO*PL": "COM"` entry should be added to `dict.json`, and the existing `"KRO*PL": "com"` entry in `dict.json` should be changed to `"KRO*PL": "{^.com}"`

But with regards to the `"KRO*PL": "com"` issue in `top-10000-english-words.json`, what should the entry change to? `"KROPL": "{^.com}"`? ``"KO*PL/KO*PL": "COM"``? Perhaps the fingerspelling of "com" (`"KR*/O*/PH*": "com"`)?

**Comment by didoesdigital** [comment]
Thanks for digging into this @paulfioravanti 

> "KROPL": ".com" in the UX dictionary should be changed to "KROPL": "{^.com}"

Agreed.

> "KO*PL/KO*PL": "COM" entry should be added to dict.json, and the existing "KRO*PL": "com" entry in dict.json should be changed to "KRO*PL": "{^.com}"

Let's do it.

> But with regards to the "KRO*PL": "com" issue in top-10000-english-words.json, what should the entry change to? "KROPL": "{^.com}"? "KO*PL/KO*PL": "COM"? Perhaps the fingerspelling of "com" ("KR*/O*/PH*": "com")?

That's a tough one. I think not the suffix because that tends to mess with the experience in Typey Type when the spacing turns out differently to people's expectations. I don't have any strong feelings on the other two options. Perhaps `"KO*PL/KO*PL": "COM"`?

**Comment by paulfioravanti** [comment]
`"KO*PL/KO*PL": "COM"` sounds fine to me. There are plenty of other acronyms in that dictionary, so it will fit in fine. I'll get a PR in that does that.
