### ISSUE TITLE
Issue with outline for "ESP"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#447]
The `dict.json` dictionary lists the correct outline for "ESP" (I'm assuming the abbreviation for Extra-Sensory Perception) as:

```
"ERBGS/S*P": "ESP"
```

However, `condensed-stroke.json` uses the same outline to for an entry for "esp" (I'm assuming for the abbreviation of "especially", perhaps...?), which is incorrect:

https://github.com/didoesdigital/steno-dictionaries/blob/4fff380513e9eb31c16d335d128399f5dc5530f3/dictionaries/condensed-strokes.json#L241

This issue is that it's the condensed stroke that is used in the Gutenberg dictionary, resulting in Typey Type picking it up:

https://github.com/didoesdigital/steno-dictionaries/blob/4fff380513e9eb31c16d335d128399f5dc5530f3/dictionaries/top-10000-project-gutenberg-words.json#L8326

If the entry in the Gutenberg dictionary is meant to be "ESP", then I think that the entry can change to `"ERBGS/S*P": "ESP"`. If it is meant to be "esp", then perhaps fingerspelling is the most appropriate? Regardless of which choice is used, I think that `"ERBGS/S*P": "esp"` can be removed from `condensed-strokes.json`.

**Comment by didoesdigital** [comment]
Thanks for this @paulfioravanti . Good catch. That makes sense, `"ERBGS/S*P": "esp"` can be removed from `condensed-strokes.json`. 

Changing the Gutenberg dictionary entry to `"ERBGS/S*P": "ESP"` also seems reasonable.
