### ISSUE TITLE
Issue with "ext" and "proc"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#46]
There are currently entries in the Typey-Type dictionaries for "ext":

https://github.com/didoesdigital/steno-dictionaries/blob/8f0c575a78fc1d204834f56cc61679a969147867/dictionaries/nouns.json#L288
https://github.com/didoesdigital/steno-dictionaries/blob/39943572e8837e031b6efdb81d995ab26c4b64e1/dictionaries/top-10000-english-words.json#L5471

and "proc":

https://github.com/didoesdigital/steno-dictionaries/blob/f98e522fd3637a7fe8b9f3cdf79544b15b25ff1c/dictionaries/code.json#L38
https://github.com/didoesdigital/steno-dictionaries/blob/39943572e8837e031b6efdb81d995ab26c4b64e1/dictionaries/top-10000-english-words.json#L6289

but neither `EGBT` nor `PROBG` exist as strokes in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) (`EGBT` does not resolve to anything, while `PROBG` resolves to "probabling").

So, since the words "ext" and "proc" are in the `top-10000-english-words.json` dictionary, and hence are used in Typey-Type, did you want to replace the strokes for these words with their finger spellings, or perhaps replace them with other words...?

**Comment by didoesdigital** [comment]
Hmm fingerspelling in `top-10000-english-words.json` is probably the best for now.
