### ISSUE TITLE
Issue with outline for "Po"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#465]
In the Gutenberg dictionary, there is the following outline for "Po":

https://github.com/didoesdigital/steno-dictionaries/blob/c8104e6321cf065b3588007fcebcfa944488fe9d/dictionaries/top-10000-project-gutenberg-words.json#L9434

However, this is the only entry for this particular spelling of "Po" in any of these dictionaries. In `dict.json`, we have:

```
"PO": "po",
"PO*": "PO",
```

So, at the very least, we have a mis-stroke here since the `PO` outline outputs "po" lowercase. 

My question then, is, does the Gutenberg dictionary give any indication as to what this entry is supposed to represent?

- If it is meant to be "Po", the chemical element polonium (or perhaps a person/thing name "Po"?), then perhaps this entry should be changed to fingerspelling.
- If it is meant to be "po", a chamber pot, then the Gutenberg entry's output should be lowercased
- If it is meant to be "PO", like an abbreviation for Post Office, then the Gutenberg entry's output should be upcased

**Comment by didoesdigital** [comment]
Nice one, @paulfioravanti !

My best guess for what an entry in the Gutenberg dictionary is meant to represent is figured out by running a search on the [Gutenberg corpus](http://www.gutenberg.org/wiki/Gutenberg:The_CD_and_DVD_Project).

With the tools I had handy, the counts suggest "po" is most used:

```
$ rg -s -j1 --no-filename -N -c -w PO .  | xargs  | sed -e 's/\ /+/g' | bc
37

$ rg -s -j1 --no-filename -N -c -w Po .  | xargs  | sed -e 's/\ /+/g' | bc
777

$ rg -s -j1 --no-filename -N -c -w po .  | xargs  | sed -e 's/\ /+/g' | bc
1401
``` 

Sampling some of the stories shows a mix of usage… 

- `Discover what there is of good and clean in the bottom of the po`
- Abbreviations for "poor" as "po'" e.g. `Po' little 'Lizabeth!`
- Deep South Negro dialect e.g. `"Well, den, one day Brer Rabbit go ter Brer Fox house, he did, en he put up mighty po' mouf. He say his ole 'oman sick, en his`
- what I'm guessing is an exclamation: `Po, po!  When the wine goes in strange things come`
- possibly including Chinese names from "The Chinese Classics": `Tsze-fu Ching-po reported the observation to Tsze-kung`
- possibly including line breaks: `"Sure, I like him," said Katy.  "He's more po- liteness than twinty candidates for Alderman, and lie makes me feel like a queen whin he walks at me side.`

**Comment by paulfioravanti** [comment]
Awesome sleuthing! I highly enjoyed being taken to language and Unix school (`brew install rg` was the next command I ran in the terminal) 😄  I'll submit a PR for this.
