### ISSUE TITLE
Plover removal of "spake"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#47]
Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) would seem to have removed the word "spake".

"spake"-related dictionary entries are currently here:

https://github.com/didoesdigital/steno-dictionaries/blob/8f0c575a78fc1d204834f56cc61679a969147867/dictionaries/nouns.json#L105
https://github.com/didoesdigital/steno-dictionaries/blob/cd65df90bda21bfbee4523ab25f973b7f2b8369b/dictionaries/top-10000-project-gutenberg-words.json#L3896

Funnily enough, the removal of "spake" from Plover does not affect the entry `"THUS/SPAEUBG/SA*R/THAOUS/TRA": "Thus Spake Zarathustra"`: this still resolves properly with `SPAEUBG` as "spake".

So, since "spake" is in the Project Gutenberg dictionary, I assume that it still warrants keeping, and therefore should the remaining strokes for the entries be changed to the finger spelling `S*/P*/A*/K*/*E`?

**Comment by didoesdigital** [comment]
Fingerspelling sounds good to me. I wonder why `spake` got removed. The Plover dict changes often leaves remnants like `"Thus Spake Zarathustra" :)
