### ISSUE TITLE
Misstrokes

### ISSUE THREAD

**Issue by user202729** [didoesdigital/steno-dictionaries#560]
Hello! Thanks for contributing! Your contribution will help new stenographers learn stenography and have a much better experience while they learn. Before you submit this issue, please check existing open and closed issues to make sure there are no duplicates. Feel free to use this template or start from scratch.  <-- this part of the template should really be in a comment by default.

# Dictionary

I noticed this dictionary entry or these dictionary entries in:

- `dict.json`

# Misstroked entry or entries

This looks like a misstroke or could otherwise be better:

```
HAPBD/SHAEUBGS hand
A/UL all
THAEURB their
A/S-P a
HARLT heart
PAOFR poor
AOEURLT either
A/A/TKPWRAOEPLT agreement
PARLTS parts
AEUPB/KHEPBLT ancient
A/A/SAOEUD aside
A/A*/A*PLT amount
A/A/ROES arose
A/A/PHRAOEU apply
A/AT/TAOUD attitude
TPAOEUPBL/HREU/HREU finally
PRO/PROE/POES/-D proposed
POL/SEU/SEU policy
KWUZ quiz
```

This looks like a misstroke because:

No comment.

# Expected

No comment.

**Comment by didoesdigital** [comment]
Thanks @user202729 ! I really appreciate you taking the time to open an issue for this and sharing all of the details. I've fixed those and updated Typey Type to match. Thanks!
