### ISSUE TITLE
README: small glitch in "Punctuation Dictionary"

### ISSUE THREAD

**Issue by YannCebron** [didoesdigital/steno-dictionaries#571]
https://github.com/didoesdigital/steno-dictionaries/#punctuation-dictionary

the entries for symbols reserved for Markdown's "list item prefix" are garbled and appear as 2nd level list item instead of their original "output character" due to missing escape:

- H-PB
- PHR*US
- STA*R

**Comment by didoesdigital** [comment]
Good catch! Thanks for filing this issue @YannCebron , it's now updated.
