### ISSUE TITLE
KPA and others use undocumented `{ }` feature

### ISSUE THREAD

**Issue by PaulColeman** [didoesdigital/steno-dictionaries#576]
In the current version of `dict.json` there is an entry `"KPA": "{ }{-|}"`.

The `{ }` isn't documented as a supported feature: https://github.com/openstenoproject/plover/wiki/Dictionary-Format

Plover's entry is: `"KPA": "{}{-|}"` (without the space in `{}`)

While Plover currently seems to do the 'right' thing with the entry, it is not working with Javelin: https://github.com/jthlim/javelin-steno/issues/7

Suggestion: for all usages of `{ }` across the repo, switch to the plover definition.

**Comment by didoesdigital** [comment]
Thanks for letting me know @PaulColeman !

That looks like a good change to make across the repo.

For my own future reference… It looks like `{ }` would [match the regex](https://github.com/openstenoproject/plover/blob/90575048b70eacd3a7610a7610d396b6dfda998b/plover/formatting.py#L122) so it might [get filtered out](https://github.com/openstenoproject/plover/blob/90575048b70eacd3a7610a7610d396b6dfda998b/plover/formatting.py#L743) and hit the [not action_list line](https://github.com/openstenoproject/plover/blob/90575048b70eacd3a7610a7610d396b6dfda998b/plover/formatting.py#L751). Maybe. 

I need to double-check my work locally before publishing but the plan is… across the repo, I'll change:

- `{ }{-|}` to `{}{-|}` or `{-|}` to match Plover
- `{ }` to ` ` or `{^ ^}`
- `{ }-{ }` to `-`
- `{ }==={ }` to `{^ === ^}`

… to produce the same behaviour and:

- `"{ }{~|()^}{#Left}"` to `"{^~| ^}{~|()^}{#Left}"`

… which should carry capitalisation better and continue to use a leading space before () regardless of previous words. 

And I'll update some test fixtures in the app to match.

**Comment by didoesdigital** [comment]
Fixed in https://github.com/didoesdigital/steno-dictionaries/commit/ddf1096aa221ccd682d08affc07e8c8371cc7907
