### ISSUE TITLE
`recall` has two briefs, one out of sync with plover's main.json

### ISSUE THREAD

**Issue by PaulColeman** [didoesdigital/steno-dictionaries#577]
# Dictionary

I noticed this dictionary entry or these dictionary entries in:

- `dict.json`

# Misstroked entry or entries

This looks like it could be better:

```json
"-RL": "recall"
"R-L": "recall"
```

# Expected

I would expect the outline to be:

```json
"-RL": "recall"
"R-L": "really"
```

This is because, without the change, there is no brief for `really`. In Plover's dictionary the outline for `really` is `R-L`.

**Comment by didoesdigital** [comment]
Thanks for letting me know @PaulColeman ! Fixed!

**Comment by didoesdigital** [comment]
https://github.com/didoesdigital/steno-dictionaries/commit/8c6b56bb22fb13a23b6d28d3f41538c31cc357d5
