### ISSUE TITLE
`of the` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#586]
# Dictionary

I noticed these dictionary entries in:
- `dict.json`

# Misstroked entry or entries
These look like misstrokes:
```json
"-FLT": "of the",
"-FTS": "of the",
"-FTD": "of the"
```

These look like misstrokes because:
- `-FLT`, `-FTS`, and `-FTD` have extraneous `-L`, `-S`, and `-D` ending sounds respectively which are not in briefs for "the" and "of" (`-T`, `-F`)
- These misstrokes mirror these that are already for the word "the" in `misstrokes.json` (`-LT`, `-TS`, `-TD`), but with `-F` added.

# Expected

I would expect the outline to be:

```json
"-FT": "of the"
```

I would expect to see that outline because:
- It is consistent with the `main.json` dictionary from Plover 3.
- It uses combination of outlines `-F` for "of" and `-T` for "the".
- It is already the shortest outline

# Even better
To make this even better, we could:
- Remove these entries completely because they can already be stroked using the outline `-FT`.

**Comment by didoesdigital** [comment]
Done! After a hard refresh, you should be able to see that the misstrokes are hidden on the [Typey Type Lookup page](https://didoesdigital.com/typey-type/lookup?q=of%20the).

<img width="858" alt="Typey Type Lookup. Enter words to look up: of the (text shown in dictionary) of the -FT typey-type.json, -FT plover-main-3-jun-2018.json (4000 misstrokes hidden.)" src="https://github.com/user-attachments/assets/28f838b5-2e04-4b3f-ab16-9841a6d06525">

Thanks again, @Monniasza !
