### ISSUE TITLE
`employed` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#587]
# Dictionary

I noticed these dictionary entries in:
- `dict.json`

# Misstroked entry or entries
These look like misstrokes or could otherwise be better:
```json
"PHROED" : "employed",
"PHOEUD" : "employed",
"PHRAOUD" : "employed",
"PHROEUDZ" : "employed",
"PWHROEUD" : "employed",
"PWHROEDZ" : "employed"
```

These look like misstrokes because:
`PHROED` is missing `U` in `OEU` for `oi` vowel
`PHOEUD` is missing `R` in `HR` for `l` starter
`PHROEUDZ` and `PWHROEUDZ` have an extra `-Z`
`PHWHROEUD` and `PWHROEUDZ` have extra `W` for the `p` starter.
`PHRAOUD` have `AOU` for `oi` instead of `OEU`

# Expected
I would expect the outline to be:

```json
"PHROEUD": "employed"
```

I would expect to see that outline because:
- It uses an elision, dropping initial "em"
- It covers the "pl" starter, "oi" vowel and "ed" ending.

# Even better

To make this even better, we could:
- Remove the entry completely because it can already be stroked without its own entry. It is not a common phrase so it does not need to appear in dictionary look up searches.

**Comment by didoesdigital** [comment]
@Monniasza, thanks for this! I've moved the misstrokes to `bad-habits.json` and sorted it, re-generated `misstrokes.json`, rebuilt the lesson data and Typey Type app, and published the changes. To see the changes, hard refresh: <https://didoesdigital.com/typey-type/lookup?q=employed>. Thanks!
