### ISSUE TITLE
`cross` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#588]
# Dictionary
I noticed this dictionary entry or these dictionary entries in:
- `dict.json`

# Misstroked entry or entries

This looks like a misstroke or could otherwise be better:

```json
"KROGS": "cross"
"KROSZ": "cross"
```

This looks like a misstroke because:
- `KROGS` has extra `-G`, which would be "crossing"
- `KROSZ` has extra `-Z`, which would be "crosses"

# Expected
I would expect the outline to be:

```json
"KROS" : "cross"
```

I would expect to see that outline because:
- It is consistent with the `main.json` dictionary from Plover 3.
- It uses `K` for hard C, `O` and `-S` for SS

**Comment by didoesdigital** [comment]
Thanks @Monniasza! The changes are live after a hard refresh: https://didoesdigital.com/typey-type/lookup?q=cross
