### ISSUE TITLE
The emoji dictionary is full of misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#592]
# Dictionary

I noticed these dictionary entries in:
- `emoji.json`

# Misstroked entry or entries
There are too many entries to show here, but you can search for following words:
```
234-6GS
23450U9/RAL
34U7B
35R9

OUTD
OULT
PHUB
TPHO*UT
TKPWHRASZ/-S
TPHAOULT/RAL
THEUFPG
WO*ERTD
HAED
SKWRAOP/TPHAOES
SKWRAP/TPHAOES
SHAOEUL/KAT
```

And some specific entries:
```
"PHOEPBLG/THEUFPG": "🤔",
"PHOEPBLG/SHAOEUL/KAT": "😸",
"PHOEPBLG/UPL/PWRAL/HRA": "☔",
"PHOEPBLG/1R*": "✌"
```

This looks like a misstroke because:
- `234-6GS`, `23450U9/RAL`, `34U7B` and `35R9` are a word stacked with the nuber key
- `OULT` and `OUTD` are misstrokes of "out"
- `SHAOEUL/KAT` is missing `P` in the first stroke for "smile"
- `PHUB` is missing the `-P` for "n" in "money"

# Even better

To make this even better, we could:
- Remove erroneous entries completely because they can already be stroked with other entries.

**Comment by didoesdigital** [comment]
Thanks @Monniasza . I'm trying to see if I can re-generate the emoji dictionary based on the current dictionaries with misstrokes removed instead of fixing each error by hand. It's taking time but I'll let you know where it ends up.

**Comment by didoesdigital** [comment]
@morinted mind if I incorporate the [`stemoji.js` script](https://github.com/morinted/stemoji/blob/master/stemoji.js) into the [Typey Type CLI](https://github.com/didoesdigital/typey-type-cli) under an MIT license? Then the Type Type CLI could generate an emoji dictionary using the latest Typey Type dictionaries (based on Plover dict minus misstrokes) whenever they're updated.

**Comment by morinted** [comment]
I don't mind at all! Sounds like a great idea.

**Comment by didoesdigital** [comment]
Yay! Thanks @morinted 🙏

**Comment by didoesdigital** [comment]
The emoji dictionary has been re-generated to use the latest dictionaries. If you add them on [Typey Type](https://didoesdigital.com/typey-type/dictionaries/management), you can see the [Lookup page](https://didoesdigital.com/typey-type/lookup) now shows the non-misstroked version:

<img width="824" alt="Lookup page shows umbrella emoji with PHOEPBLG/UPL/PWREL/HRA" src="https://github.com/user-attachments/assets/8cf733bc-04fe-490f-a4a9-515f4acccfbd">

**Comment by didoesdigital** [comment]
The stemoji script was added to the CLI in https://github.com/didoesdigital/typey-type-cli/pull/9

Thanks for raising this issue @Monniasza ! There were a fair few changes made to the emoji dictionary. It cleared out a lot of misstrokes. Feel free to open a new issue for any additional misstroke entries.
