### ISSUE TITLE
`cancer` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#601]
# Dictionary
I noticed this dictionary entry or these dictionary entries in:
- `dict.json`
- `dict-en-AU-with-extra-stroke.json`

# Misstroked entry or entries
These looks like misstrokes or could otherwise be better:
```json
"SKEFR": "cancer",
"SKRER": "cancer",
"SK*ER": "cancer",
"SKERPB": "cancer"
```

This looks like a misstroke because:
- `SKEFR` has extra `-F` -> "cancever"
- `SKRER` has extra `R` -> "cansrer"
- `SK*ER` has extra `*`
- `SKERPB` has extra `-PB` -> "cancern"

# Expected
I would expect the outline to be:
```json
"SKER": "cancer"
```
I would expect to see that outline because:
- It is a brief
- It is consistent with the `main.json` dictionary from Plover 3.

# Even better
To make this even better, we could:
- Remove entries completely because they can already be stroked without their own entries.

**Comment by didoesdigital** [comment]
Thanks @Monniasza ! Fixed and published.
