### ISSUE TITLE
`medically` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#602]
Hi. I've found that `"PHEL/HREU": "medically"` is a valid outline for "medically". It misses the 'd' in one of the strokes. It sounds like a misstroke. `PHED/KHREU` sounds better.

Please move the `"PHEL/HREU": "medically"` to misstrokes.

**Comment by didoesdigital** [comment]
Thanks @Monniasza ! Fixed and published.
