### ISSUE TITLE
`cancellation` misstroke

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#604]
# Dictionary

I noticed this dictionary entry in:
- `dict.json`

# Misstroked entry or entries
This looks like a misstroke or could otherwise be better:
```json
"APBS/HRAEUGS": "cancellation",
```

This looks like a misstroke because:
- The first stroke misses `K` in `KAPBS`
 
# Expected
I would expect the outline to be:
```json
"KAPBS/HRAEUGS": "cancellation"
```

I would expect to see that outline because:
- It adds the missing 'k' sound at the beginning

**I also suggest the brief `SKELGS`**, formed with "cancel"`SKEL` + "-ation"`-GS`

# Even better
To make this even better, we could:
- Remove the entry completely because it can already be stroked without its own entry.

**Comment by didoesdigital** [comment]
Good spot @Monniasza ! When I get a moment, I'll remove it

**Comment by Monniasza** [comment]
@didoesdigital The `SKELGS` has been added to Typey Type, but `APBS/HRAEUGS` is still the preferred stroke in Typey Type.

**Comment by didoesdigital** [comment]
Thanks @Monniasza , I'll see about fixing that up.

**Comment by didoesdigital** [comment]
I've added `"SKELGS": "cancellation"`, thanks @Monniasza !
