### ISSUE TITLE
`extra` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#605]
# Dictionary
I noticed these dictionary entries in:
- `dict.json`
- `dict-en-AU-with-extra-stroke.json`

# Misstroked entries
These look like misstrokes or could otherwise be better:

```json
"TRAEBGS": "extra",
"ERBGS/TRA": "extra"
```

These looks like misstrokes because:
- `TRAEBGS` has the starter and ending reversed
- `ERBGS/TRA` has extra `-R` on the first stroke

# Expected

I would expect the outlines to be:

```json
"KPRA": "extra",
"EBGS/TRA": "extra"
```

I would expect to see those outlines because:
- `KPRA` is a brief
- `EBGS/TRA` is a canonical outline

# Even better
To make this even better, we could:
- Remove entries completely because they can already be stroked without their own entry.

**Comment by didoesdigital** [comment]
Thanks @Monniasza ! Agreed, I'll fix these up when I get a chance.

**Comment by didoesdigital** [comment]
I've published these changes. Thanks @Monniasza !
