### ISSUE TITLE
`scary` misstroke

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#607]
# Dictionary
I noticed this dictionary entry or these dictionary entries in:
- `dict.json`
# Misstroked entry or entries
This looks like a misstroke or could otherwise be better:
```json
"SKWAER": "scary",
```
This looks like a misstroke because:
- `SKWAER` has extra `W`, which does not exist in the translation's pronounciation

# Expected

I would expect the outline to be:

```json
"SKAER": "scary",
"SKAEUR/KWREU": "scary"
```

I would expect to see that outline because:
- `SKAER` is a bries, using E-folding for 'a' + '-y'
- `SKAEUR/KWREU` is the canonical outline for "scary", a combination of 'scare' + '-y'.

# Even better
To make this even better, we could:
- Remove the entry completely because it can already be stroked without its own entry.

**Comment by didoesdigital** [comment]
Thanks @Monniasza ! It's updated now https://didoesdigital.com/typey-type/lookup?q=scary
