### ISSUE TITLE
`sex` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#608]
# Dictionary
I noticed these dictionary entries in:
- `dict.json`
- `dict-en-AU-with-extra-stroke.json`

# Misstroked entries

These look like misstrokes or could otherwise be better:

```json
"SPHEBGS": "sex",
"SPHEBGTS": "sex",
"STPHEBGS": "sex",
"SPH*EBGS": "sex"
```

This looks like a misstroke because:

- `SPHEBGS`, `SPHEBGTS` and `SPH*EBGS` have initial `PH`, where 'm' is not present in the translation
- `SPHEBGTS` has ending `-T`, where there's no 't' sound
- `STPHEBGS` has extra `TPH`, without the 'n' sound

# Expected
I would expect the outline to be:
```json
"S-BGS": "sex"
```
I think that "`SEBGS` is appropriate, but it's already taken by 'section".

I would expect to see that outline because:
- It is a skeletal brief

# Even better
To make this even better, we could:
- Remove entries completely because they can already be stroked without their own entries.

**Comment by didoesdigital** [comment]
Thanks @Monniasza , removed those entries
