### ISSUE TITLE
Issue with stroke for "quitted"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#61]
The dictionaries currently have a stroke entry for the word "quitted" here:

https://github.com/didoesdigital/steno-dictionaries/blob/9412f77b9bcdfe40a8ad60d890e815e6745e9450/dictionaries/top-10000-project-gutenberg-words.json#L5265

 Regardless of "quitted" [still being a valid past-participle of "quit"](https://en.wiktionary.org/wiki/quit#Verb), Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) does not have an entry for it, which is causing issues when it comes up in Typey-Type. Also, the current stroke for "quitted" in the dictionary, `KWEUT/-D`, results in "quited" being output.

Since there is no stroke for a `{^ted}` output in the same vein of `"-D": "{^ed}"`, unless there is a way of stroking "quitted" some other way, I would think that the stroke for this entry would need to be changed to its fingerspelling. What do you think?

**Comment by didoesdigital** [comment]
Good find @paulfioravanti . Fingerspelling sounds like a good approach here. Otherwise, `KWEUT/T*/-D` or `KWEUT/T*/*E/TK*`. Up to you.

**Comment by paulfioravanti** [comment]
Since `KWEUT/T*/-D` and `KWEUT/T*/*E/TK*` would both seem to result in "quit ted" with a space, I would agree with you that fingerspelling is probably the best approach.
