### ISSUE TITLE
`"APBS/HRAEUGS": "cancellation"` has not been removed from Typey Type even though it is classifed as a misstroke

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#611]
Concerning #604, the aforementioned misstroke has not been removed yet from Typey Type or the dictionary, but `SKELGS` is now the preferred outline for "cancellation", but the misstroke is still prominent.

**Comment by didoesdigital** [comment]
Oops! Fixed that: https://didoesdigital.com/typey-type/lookup?q=cancellation

Thanks @Monniasza
