### ISSUE TITLE
`they're` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#615]
# Dictionary
I noticed these dictionary entries in:
- `dict.json`

# Misstroked entry or entries
These look like misstrokes or could otherwise be better:
```json
"THERB": "they're",
"THA*EUR": "they're"
```
These look like misstrokes because:
- `THERB` has extra `-B`
- `THA*EUR` reminds me of `their`, a common misspelling of "they're"

Also, `"THER/AE": "they're"` has unnecessary apostrophe stroke.

# Expected

I would expect the outline to be:

```json
"THER": "they're"
```

I would expect to see that outline because:

- It uses a suffix stroke.
- It is consistent with the `main.json` dictionary from Plover 3.
- It consists of `"THE": "they"` and `"-R": "are"`

# Even better
To make this even better, we could:
- Remove the entries completely because they can already be stroked without their own entries

**Comment by didoesdigital** [comment]
Thanks @Monniasza 

I think `"THA*EUR": "they're"` belongs to this set of briefs of a similar structure:

```
"THA*EUD": "they'd",
"THA*EUF": "they've",
"THA*EUL": "they'll",
"THA*EUR": "they're",
```

I'm inclined to keep it for consistency with the set.

I've removed `"THERB": "they're",` https://didoesdigital.com/typey-type/lookup?q=they're
