### ISSUE TITLE
Issue with stroke for "picked"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#68]
In the current `dict.json` file, there are the following strokes for the word "picked", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PEUBG/-D": "picked",
"PEUBG/-DZ": "picked",
"PEUBGD": "picked",
"PEUBGTD": "picked",
"PEUGD": "picked",
"TPEUBG/-D": "picked",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "picked" used is `"PEUGD": "picked"`, and I'm wagering that this is the stroke that came up for me on Typey-Type.

Even though `"PEUGD"` is the shortest Plover-recognised stroke for `"picked"`, I would have expected to see `"PEUBGD"` instead, with the full `BG` stroke for "k" (although, it does also sound "right" having a "g" sound substitute for a "k" sound). So, my question is: is `PEUGD` a mis-stroke for `PEUBGD` (and hence the entry in the Gutenberg dictionary should change), or is it fine as it is?

**Comment by didoesdigital** [comment]
Good catch, @paulfioravanti ! `PEUGD` looks like a misstroke to me, missing the `B`. Yes, that should change in the Gutenberg dictionary, and moved from `dict.json` to `bad-habits.json`.

These also look like misstrokes to me:

```
"TPEUBG/-D": "picked",
"TPEUBG/-S": "picks",
"PEUBGTD": "picked",
```

… where they all have an unnecessary `T` and I would expect the last one to be "picketed" to match `"PEUBGT": "picket",` and `"PEUBGT/-D": "picketed",`

**Comment by paulfioravanti** [comment]
Okay, cool. Just to confirm, I'll put in a PR that:

- moves the following entries for into `bad-habits.json`:
```json
"PEUGD": "picked",
"TPEUBG/-D": "picked",
"PEUBGTD": "picked",
"TPEUBG/-S": "picks",
```
- changes the stroke entry for "picked" in `top-10000-project-gutenberg-words.json` from `"PEUGD"` to `"PEUBGD"`
