### ISSUE TITLE
Issue with stroke for "bless"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#71]
In the current `dict.json` file, there are the following strokes for the word "bless", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PWHRES": "bless",
"PWHRESZ": "bless",
"PWRES": "bless",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "bless" used is `"PWRES": "bless"`, and I'm wagering that this is the stroke that came up for me on Typey-Type.

Even though `"PWRES"` is the shortest Plover-recognised stroke for `"bless"`, I would have expected to see `"PWHRES"` instead, with the full `HR` stroke for "l". So, my question is: is `PWRES` a mis-stroke for `PWHRES` (and hence the entry in the Gutenberg dictionary should change), or is it fine as it is?

**Comment by didoesdigital** [comment]
`"PWRES": "bless",` looks like a misstroke to me that should be moved to `bad-habits.json` and updated in `top-10000-project-gutenberg-words.json`
