### ISSUE TITLE
Issue with stroke for "blast"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#76]
In the current `dict.json` file, there are the following strokes for the word "blast", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PWRAFT": "blast",
"PWHRA*S": "blast",
"PWHRAFT": "blast",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "blast" used is `"PWRAFT": "blast"`, and this is the stroke that comes up on Typey-Type.

Given that `PWRAFT` is missing the `H` for the "L" stroke, and given that it seems that every other dictionary entry that has "blast" as part of its word uses the full `PWHRAFT` stroke, I looks to me that `PWRAFT` may be a mis-stroke.

If that is the case, I'd like to propose:

- Moving `"PWRAFT": "blast",` to `bad-habits.json`
- Changing the entry in `top-10000-project-gutenberg-words.json` to `PWHRAFT`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti . That sounds good to me.
