### ISSUE TITLE
Issue with stroke for "folds"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#77]
In the current `dict.json` file, there are the following strokes for the word "folds", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"TPOLDZ": "folds",
"TPOELDZ": "folds",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "folds" used is `"TPOLDZ": "folds"`, and this is the stroke that comes up on Typey-Type. It came up for me in the same practice word set as singular "fold", which has the single stroke `TPOELD`. 

It struck me as strange that the singular and plural of a word would have a different stroke for their "O" sounds, so I was wondering if perhaps:

- `"TPOLDZ": "folds"` is a mis-stroke, and should be moved into `bad-habits.json`?
- Regardless of whether `TPOLDZ` is a mis-stroke or not, should the entry in `top-10000-project-gutenberg-words.json` be changed to `"TPOELDZ": "folds"`, to give it a symmetry with `"TPOELD": "fold"` ?

**Comment by didoesdigital** [comment]
Interesting one, @paulfioravanti .

From the [Learn Plover book](https://sites.google.com/site/ploverdoc/lesson-1-fingers-and-keys?authuser=0):

> Rule 1: If the vowel letter in the written word appears without another vowel letter next to it, then it doesn't matter which short vowel sound it makes. The Plover key labeled with that letter is always used to stroke the word.
> So 'not' is stroked with O because it's spelled with "o", and 'tar' is stroked with A because it's spelled with "a". Likewise, 'pert' uses E and 'purse' uses U.

So if anything `FOELD` and `FOELDZ` should be misstrokes and `FOLD` should be the phonetic stroke for "fold" but it's occupied by the brief for "followed".

To avoid straying too far from Plover's dictionary, I think it's best to leave them as they are even though it contradicts the theory a little.

We could update the Top 10000 Project Gutenberg words lesson to use FOELDZ for symmetry. I don't have strong feelings on whether to change it or not. Up to you @paulfioravanti

**Comment by paulfioravanti** [comment]
Thanks for that, @didoesdigital!

> To avoid straying too far from Plover's dictionary, I think it's best to leave them as they are even though it contradicts the theory a little.

Yep, I agree with this, especially since `TPOELD` is the _only_ Plover entry for "fold", with `TPOLD` being for "followed". Normally, I'd be inclined to go with symmetry, but, in this case, changing it could potentially raise further questions by future Typey-Type users, so I think we can just close this issue out.
