### ISSUE TITLE
Issue with stroke for "clutch"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#81]
In the current `dict.json` file, there are the following strokes for the word "clutch", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"HRUFP": "clutch",
"KHRUFP": "clutch",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "clutch" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/70f70bcedeeca5c4b4f71b85a7dc9f5962330f37/dictionaries/top-10000-project-gutenberg-words.json#L9942 

Even though `"HRUFP"` is the shortest Plover-recognised stroke for "clutch", I would have expected to see `"KHRUFP"` instead, with the added `K` stroke for "c". So, my question is: is `HRUFP` a mis-stroke for `KHRUFP` (and hence the entry in the Gutenberg dictionary should change), or is it fine as it is?

In Plover, the stroke for "clutched" is ` KHRUFPD`, which further makes me think this could be a candidate for `bad-habits.json`.

**Comment by didoesdigital** [comment]
@paulfioravanti  looks like a misstroke to me. Moving it to bad habits and updating the Gutenberg dictionary sounds good. 

Good approach checking "clutched" 👏
