### ISSUE TITLE
Issue with stroke for "edge"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#83]
In the current `dict.json` file, there are the following strokes for the word "edge", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"EPBG": "edge",
"EPBLG": "edge",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "edge" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/17a61a2937dbaa3fbea7cafcaa97da3c14f677ff/dictionaries/top-10000-project-gutenberg-words.json#L1493

Even though `"EPBG"` is the shortest Plover-recognised stroke for "edge", I would have expected to see `"EPBLG"` instead, with the added `L` for the full stroke for the "j" sound (`PBLG`).

Given that:

1. "edges" plural in the Gutenberg dictionary uses the full stroke

https://github.com/didoesdigital/steno-dictionaries/blob/17a61a2937dbaa3fbea7cafcaa97da3c14f677ff/dictionaries/top-10000-project-gutenberg-words.json#L5993

2. The stroke for "edge" variations in `dict.json` use the full `EPBLG` stroke

```json
"*EPBLG/PHOPBT": "edgemont",
"EPBLG/ER": "edger",
"EPBLGD": "edged",
"EPBLGS": "edges",
```

Is `EPBG` a mis-stroke for `EPBLG` (and hence the entry in the Gutenberg dictionary should change, as well as the entry moved to `bad-habits.json`)?

**Comment by didoesdigital** [comment]
Thanks for this @paulfioravanti. That all sounds right to me. It's great to see how you're getting the hang of the theory, spotting misstrokes, and validating them against other strokes in the dictionary.

✅ `EPBG` a mis-stroke for `EPBLG` (and hence the entry in the Gutenberg dictionary should change, as well as the entry moved to `bad-habits.json`)
