### ISSUE TITLE
Issue with stroke for "clean"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#84]
In the current `dict.json` file, there are the following strokes for the word "clean", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"KHAOEPB": "clean",
"KHRAOEB": "clean",
"KHRAOEPB": "clean",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "clean" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/17a61a2937dbaa3fbea7cafcaa97da3c14f677ff/dictionaries/top-10000-project-gutenberg-words.json#L1723

Even though `KHAOEPB` is the equal shortest Plover-recognised stroke for "edge" (along with `KHRAOEB`) I would have expected to see the full `KHRAOEPB`stroke  instead, with full strokes for the "l" (`HR`) and "n" (`PB`) sounds.

Given that:

1. "unclean" and "cleaning" in the Gutenberg dictionary use the full `KHRAOEPB` stroke for "clean"

https://github.com/didoesdigital/steno-dictionaries/blob/17a61a2937dbaa3fbea7cafcaa97da3c14f677ff/dictionaries/top-10000-project-gutenberg-words.json#L8523

https://github.com/didoesdigital/steno-dictionaries/blob/17a61a2937dbaa3fbea7cafcaa97da3c14f677ff/dictionaries/top-10000-project-gutenberg-words.json#L9379

2. The strokes for "clean" variations in `dict.json` use the full `KHRAOEPB` stroke

```json
"KHRAOEPB/*ER": "cleaner",
"KHRAOEPB/-G": "cleaning",
"KHRAOEPB/ERS": "cleaners",
"KHRAOEPB/HREU/TPH-S": "cleanliness",
"KHRAOEPB/SKWRUP": "clean-up",
"KHRAOEPBD": "cleaned",
"KHRAOEPBG": "cleaning",
"KHRAOEPBL": "cleanly",
"KHRAOEPBS": "cleans",
"KHRAOERPB": "cleaner",
"TKHRAOEPB": "clean it",
"TKRAOEU/KHRAOEPB/*ER": "dry-cleaner",
"UPB/KHRAOEPB": "unclean",
```

Are `KHAOEPB` and `KHRAOEB` mis-strokes for `KHRAOEPB` (and hence their entries in the Gutenberg dictionary should change, as well as the entries moved to `bad-habits.json`)?

**Comment by didoesdigital** [comment]
Thanks for the issue @paulfioravanti. That all sounds right to me. 

✅ `KHAOEPB` and `KHRAOEB` mis-strokes for KHRAOEPB (and hence their entries in the Gutenberg dictionary should change, as well as the entries moved to `bad-habits.json`)
