### ISSUE TITLE
Issue with stroke for "hedge"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#85]
In the current `dict.json` file, there are the following strokes for the word "hedge", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"HEPBL": "hedge",
"HEPBLG": "hedge",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "hedge" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/17a61a2937dbaa3fbea7cafcaa97da3c14f677ff/dictionaries/top-10000-project-gutenberg-words.json#L5887

Even though `HEPBL` is the shortest Plover-recognised stroke for "hedge", I would have expected to see `HEPBLG` instead, with full `PBLG` stroke for the "j" sound.

Given that:

1. The stroke for "hedgehog" in `dict.json` uses the full `HEPBLG` stroke:

```json
"HEPBLG/HOG": "hedgehog",
```

2. It would seem that `HEPBL` doesn't look technically like a mis-stroke(?) since its also used for single-stroke  "hedged", along with `HEPBLG`

```json
"HEPBLDZ": "hedged",
"HEPBLGD/-D": "hedged",
```

I would propose:

- Changing at least the stroke entry for "hedge" in `top-10000-project-gutenberg-words.json` from `HEPBL` to `HEPBLG`
- Either, depending on your opinion:
  - Leave `HEPBL`-based entries in `dict.json` as they are
  - Move `HEPBL`-based entries ("hedge" and/or "hedged") to `bad-habits.json`

**Comment by didoesdigital** [comment]
Thanks for writing this up, @paulfioravanti.

> Changing at least the stroke entry for "hedge" in `top-10000-project-gutenberg-words.json` from `HEPBL` to `HEPBLG`

✅Sounds good to me.

Given the phonetics, Plover theory, and the stroke for "hedgehog" in point 1, I would expect to see `"HEPBLGD": "hedged",`. This stroke works for me anyway, presumably using Plover's automatic `-D` suffix and orthography rules. It's possible `"HEPBLDZ"` might be a misstroke, missing the `G` and [dragging](https://github.com/openstenoproject/plover/wiki/Glossary#dragging) or erroneously hitting the `Z`. It's possible `"HEPBLGD/-D"` might be a misstroke, successfully writing `hedged` on the first stroke using the Plover rules and erroneously hitting `/-D` again.

I would also expect to see `"HEPBLGS": "hedges",` or `"HEPBLGZ": "hedges",` for the plural of hedge, but that doesn't seem to appear at all.

It might be worth proposing some changes to [Plover's issue 400](https://github.com/openstenoproject/plover/issues/400).

For now, on the balance, I'd say:

✅ Move `HEPBL`-based entries ("hedge" and/or "hedged") to `bad-habits.json`.
