### ISSUE TITLE
Issue with stroke for "dealing"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#92]
In the current `dict.json` file, there are the following strokes for the word "dealing", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"TAOELG": "dealing",
"TKAOEG": "dealing",
"TKAOEL/-G": "dealing",
"TKAOELG": "dealing",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "dealing" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L4096

Although Plover says it's a valid stroke, I am wondering whether perhaps `TAOELG` is a mis-stroke due to it not having the full `TK` stroke for "d", which is what I would have expected for the word "dealing".

Given that:

Strokes using "deal" in every other entry in `dict.json` use the full `TK` stroke for "d":

```json
"TKAOEG": "dealing",
"TKAOEL": "deal",
"TKAOEL/*ER": "dealer",
"TKAOEL/*ER/AES": "dealer's",
"TKAOEL/*ER/SH-P": "dealership",
"TKAOEL/*ERS/AE": "dealers'",
"TKAOEL/-G": "dealing",
"TKAOEL/ER/SHEUP": "dealership",
"TKAOEL/ER/SHEUPS": "dealerships",
"TKAOEL/ERS": "dealers",
"TKAOEL/KWREU/-S": "dealies",
"TKAOEL/KWREU/O*": "dealio",
"TKAOEL/KWREU/PWOB": "dealybob",
"TKAOELD": "dealed",
"TKAOELG": "dealing",
"TKAOELG/*ER": "dealer",
"TKAOELGS": "dealings",
"TKAOELS": "deals",
"TKAOERL": "dealer",
"TKELT": "dealt",
"TKWAOEL": "deal with",
"TKWAOELG": "dealing with",
"TKWAOELS": "deals with",
```

I would propose:

- Removing `"TAOELG": "dealing"` from `dict.json`
- Adding `"TAOELG": "dealing"` to `bad-habits.json`
- Changing the stroke for "dealing" in `top-10000-project-gutenberg-words.json` from `TAOELG` to `TKAOELG`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti, those changes look great.
