### ISSUE TITLE
Change proposal for Typey-Type stroke for "major"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#93]
In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "major" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L4109

`PHAEUPBLG` is also another valid stroke for "major" in Plover, and I think this stroke, with the elongated "ā" sound, is more of a natural fit for the word "major" than the `PHOEUPBLG` stroke with the "oi" (`OEU`) sound.

So, I would like to propose changing the stroke used for "major" in `top-10000-project-gutenberg-words.json` from `PHOEUPBLG` to `PHAEUPBLG`. What do you think?

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti, that makes sense to me. I expect it's chosen `PHOEUPBLG` over `PHAEUPBLG` for no other reason than it appears first.
