### ISSUE TITLE
Issue with stroke for "estimation"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#95]
In the current `dict.json` file, there are the following single-stroke entries for the word "estimation", both of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"STEUPGS": "estimation",
"STEUPLGS": "estimation",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "estimation" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L7092

Although Plover says it's a valid stroke, I am wondering whether perhaps `STEUPGS` is a mis-stroke due to it not having the full `PL` stroke for "m", which is what I would have expected for the word "estimation".

Given that:

Other two-stroke entries for "estimation" in `dict.json` use the full `PL` stroke for "m":

```json
"STEUPL/AEUGS": "estimation",
"STEUPLT/AEUGS": "estimation",
```

I would propose:

- Removing `"STEUPGS": "estimation"` from `dict.json`
- Adding `"STEUPGS": "estimation"` to `bad-habits.json`
- Changing the stroke for "dealing" in `top-10000-project-gutenberg-words.json` from `STEUPGS` to `STEUPLGS`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti, sounds good to me.
