### ISSUE TITLE
No Plover stroke for "civilisation"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#96]
In the current dictionaries, there are the following entries for the word "civilisation":

https://github.com/didoesdigital/steno-dictionaries/blob/564ffc3b104d000517daf58eb8da0f4b67a1fd1c/dictionaries/nouns.json#L122

https://github.com/didoesdigital/steno-dictionaries/blob/c8bbf3bc9edacec506986c6cf0e84b83448f84b4/dictionaries/top-10000-project-gutenberg-words.json#L7236

In what I see as an extremely unfortunate oversight, Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) does not have an entry for "civilisation" with an "s" 😞 `S*EUFLGS` instead outputs "syphilising".

So, I guess the options for changing the current entries could be a combination of any of these options:

For the `nouns.json` entry:

a) Changing the entry to `"SEUFLGS": "civilization"` (since there is no "civilization" entry in that dictionary
b) Remove it completely without replacing it
c) Change the "civilisation" entry to its finger spelling: `KR*/*EU/SR*/*EU/HR*/*EU/S*/A*/T*/*EU/O*/TPH*`

For the `top-10000-project-gutenberg-words.json` entry:

a) Change the "civilisation" entry to its finger spelling: `KR*/*EU/SR*/*EU/HR*/*EU/S*/A*/T*/*EU/O*/TPH*` (I'm putting this as the first option since this dictionary _also_ has a `"SEUFLGS": "civilization"` entry, and I'm assuming that you won't want to remove the "civilisation" entry entirely to bring the dictionary word count to 9999 words)
b) Perhaps pick another word to substitute for this word, as the "civilisation" finger spelling is a long one (I would have questioned whether it was normal to have different regional spellings of the same word in the `top-10000-project-gutenberg-words.json` dictionary, but then I saw that there are separate entries for words like "color"/"colour", "favor"/"favour" etc)

What would be a good compromise in this case?

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. This is a pesky one!

I generally want to leave the words as they are as much as possible in the Gutenberg dictionary to match the source material it comes from, even if it weirdly has multiple regional spellings, and to keep it at 10000 words.

I'm having doubts about the `nouns.json` dictionary. I've grown it over the years in multiple directions e.g. chunking up the main Plover dictionary, adding "condensed strokes" before I gave that its own dictionary, and potential "new words" to include like "celeriac". I think I'll file a new issue to fix that.

Of the options you suggest for `top-10000-project-gutenberg-words.json`, I would prefer to fingerspell it.

One other possibility, however, is that we make a new condensed stroke entry for it (updating in the `top-10000-project-gutenberg-words.json` and adding to `condensed-strokes.json`). For example:

- `"SEUFL/*EU/S*/A*/T*/*EU/O*/TPH*": "civilisation",
- `"SEUFL/*EU/SAEUGS": "civilisation",` using the suffix entry for `"SAEUGS": "{^sation}",`

For now, let's:

- Delete `"S*EUFLGS": "civilisation",` from `nouns.json`.
- Add `"SEUFLGS/A*U": "civilisation",` to `dict-en-AU-with-extra-stroke.json`.
