### ISSUE TITLE
Issue with stroke for "secondly"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#97]
In the current `dict.json` file, there are the following strokes for the word "secondly", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"SEBG/TKHREU": "secondly",
"SEBGD/HREU": "secondly",
"SEBLGD": "secondly",
"SELGD": "secondly",

```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "secondly" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L7590

Although Plover says it's a valid stroke, I am wondering whether perhaps `SELGD` is a mis-stroke due to it not having the `BG`-stroke-for-"k" included in its stroke, which is what at least I would have expected for the word "secondly".

Given that:

The two-stroke entries for "secondly" in `dict.json` use the full `BG` stroke for their "k" sound:

```json
"SEBG/TKHREU": "secondly",
"SEBGD/HREU": "secondly",
```

I would propose:

- Removing `"SELGD": "secondly",` from `dict.json`
- Adding `"SELGD": "secondly",` to `bad-habits.json`
- Changing the stroke for "secondly" in `top-10000-project-gutenberg-words.json` from `SELGD` to `SEBLGD`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. That all sounds good to me.

One other possibility is that `"SELGD": "secondly",` was attempting to riff on `*LG` for "lk" sounds for a kind of inversion based brief version of "selkd", but that would still be a misstroke missing the `*`.
