### ISSUE TITLE
No single-stroke Plover entry for "expansion"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#98]
In `top-10000-project-gutenberg-words.json`, the stroke used for the word "expansion" is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L7660

It would seem to take this from the `briefs.json` dictionary:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/briefs.json#L107

The problem here is that there is no single-stroke entry for "expansion" in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), only two-stroke entries:

```
expansion:
   EBGS/PAPBGS
   EBGS/TAPBGS
   EBGS/KPAPBGS
```

Given this scenario, what action is best to take?

- Remove `"KPAPBGS": "expansion"` from `briefs.json` (and maybe add it to `bad-habits.json`)?
- Change the `top-10000-project-gutenberg-words.json` entry for "expansion" to another stroke? If so, my vote would be for `"EBGS/PAPBGS": "expansion"`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. Similar to the problems in https://github.com/didoesdigital/steno-dictionaries/issues/96, I've muddled `briefs.json` and need to clean it up in #123 .

In the meantime, yes, let's remove `"KPAPBGS": "expansion"` from `briefs.json`, but not add it to `bad-habits.json`, and change the `top-10000-project-gutenberg-words.json` entry for "expansion" to `EBGS/PAPBGS`. 

We could also move `EBGS/TAPBGS` into `bad-habits.json` as a misstroke using `T` where it should be `P` and move `EBGS/KPAPBGS` into `bad-habits.json` as a misstroke for using `KP` for an "x" sound, which is redundant with `EBGS`.
