### ISSUE TITLE
Issue with stroke for "violation"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#99]
In the current `dict.json` file, there are the following strokes for the word "violation", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"SRAOEU/HRAEUGS": "violation",
"SRAOEUL/AEUGS": "violation",
"SRAOEUL/HRAEUGS": "violation",
"SRAOEULGS": "violation",
"SREU/HRAEUGS": "violation",
"SROEULGS": "violation",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "violation" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L7698

Although Plover says it's a valid stroke, I feel that `"SRAOEULGS": "violation"` with the elongated "ī" sound (`AOEU`) is a more accurate entry pronunciation-wise, and so would like to propose:

- Changing the stroke for "violation" in `top-10000-project-gutenberg-words.json` from `SROEULGS` to `SRAOEULGS`

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti, sounds good to me.
